const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const E=require('../shared/evidence-ui.js'),Y=require('../shared/yard-opportunities.js');
const now=Date.parse('2026-09-21T18:00:00Z');
test('explicit injury laterality highlights only the reported side',()=>{const dom=new JSDOM(E.anatomy({primary_injury:'Left knee',secondary_injury:'Right shoulder'}));const selected=[...dom.window.document.querySelectorAll('.affected')].map(e=>e.dataset.region);assert.deepEqual(selected.sort(),['knee-left','shoulder-right']);dom.window.close();});
function fixture(){const board={generated_at:'2026-09-21T17:00:00Z',games:[{game_pk:1,home:'BAL',away:'TOR',time:'2026-09-21T22:00:00Z'}],players:[{id:1,name:'Test Player',game_pk:1,heat:68,hit_heat:60,hrr_heat:63,why:'Published evidence',lineup_status:'confirmed',metrics:{barrel_pct:{recent:12}},sample:{L15:52}}]};const quote={name:'Test Player',home_team:'Baltimore Orioles',away_team:'Toronto Blue Jays',line:.5,last_update:'2026-09-21T17:58:00Z',books:{draftkings:500}};return{board,odds:{slate_date:'2026-09-21',prices:{test:quote}},quote};}
test('compact charts show finite real values only and do not fabricate missing metrics',()=>{const html=E.panel([{label:'Missing',value:null},{label:'Zero',value:0,max:1},{label:'Bad',value:NaN}]);assert.match(html,/Zero/);assert.doesNotMatch(html,/Missing|Bad|NaN/);});
test('injury figure maps multiple reported regions and leaves unknown locations unhighlighted',()=>{assert.deepEqual(E.regions('Shoulder / ankle / hamstring'),['shoulder','thigh','foot']);assert.match(E.anatomy({primary_injury:'Illness',report_status:'Questionable'}),/No anatomical location was inferred/);assert.doesNotMatch(E.anatomy({primary_injury:'Illness'}),/<svg/);assert.equal(E.anatomy(null),'');assert.match(E.anatomy({primary_injury:'Knee',practice_status:'Limited'}),/affected/);});
test('MLB cards retain published score, source and sportsbook without inventing probabilities',()=>{const f=fixture(),rows=Y.build(f.board,f.odds,now);assert.equal(rows.length,1);assert.equal(rows[0].strength,68);assert.equal(rows[0].book,'draftkings');assert.equal(rows[0].odds,500);assert.equal(rows[0].prob,undefined);assert.match(rows[0].projectionLabel,/research strength/);});
test('MLB rejects stale prices, wrong opponents, doubleheader ambiguity and inactive players',()=>{for(const mutate of [f=>f.quote.last_update='2026-09-19T17:00:00Z',f=>f.quote.home_team='Boston Red Sox',f=>f.board.games.push({...f.board.games[0],game_pk:2}),f=>f.board.players[0].lineup_status='out',f=>f.odds.slate_date='2026-09-20']){const f=fixture();mutate(f);assert.equal(Y.build(f.board,f.odds,now).length,0);}});
test('MLB decimal prop quotes retain the exact line and every offered book',()=>{const f=fixture();f.odds.props={hits:{test:{...f.quote,books:{draftkings:{line:.5,over:1.8},fanatics:{line:.5,over:2.1}}}}};assert.equal(Y.build(f.board,f.odds,now).length,3);f.odds.props.hits.test.books.fanatics.line=1.5;assert.equal(Y.build(f.board,f.odds,now).length,2);});
test('shared slip persists cross-sport legs and refuses same-game/cross-book ticket estimates',()=>{const dom=new JSDOM('<body></body>',{url:'https://example.test',runScripts:'outside-only'});const w=dom.window;for(const file of ['evidence-ui.js','opportunity-ui.js'])w.eval(fs.readFileSync(path.join(__dirname,'../shared',file),'utf8'));const row={id:'n',sport:'nfl',event:'a',book:'draftkings',odds:110,kickoff:new Date(Date.now()+3600000).toISOString(),updatedAt:new Date().toISOString(),label:'NFL pick'};w.GoingUI.add(row);w.GoingUI.add({...row,id:'m',sport:'mlb',event:'b',label:'MLB pick'});assert.equal(w.GoingUI.read().length,2);assert.match(w.document.body.textContent,/price product/);w.GoingUI.write([row,{...row,id:'m',book:'fanatics'}]);assert.match(w.document.body.textContent,/Different books/);assert.doesNotMatch(w.document.body.textContent,/price product/);dom.window.close();});
test('public football adapter preserves frozen features and never admits post-kickoff predictions',async()=>{const {footballRecords}=await import('../scripts/build_consumer_data.mjs');const p={id:'1',sport:'nfl',kickoff:'2026-09-21T20:00:00Z',observed_at:'2026-09-21T19:00:00Z',tracking_group:'best_model',model_evidence:{n:12},probability:.4};const rows=footballRecords({records:[{kind:'prediction',payload:p},{kind:'prediction',payload:{...p,id:'2',observed_at:'2026-09-21T21:00:00Z'}}]});assert.equal(rows.length,1);assert.equal(rows[0].features.probability,.4);assert.equal(rows[0].sample_sizes.games,12);assert.equal(rows[0].outcome,null);});
