import React,{useEffect,useState} from 'react';
import {gameDiagnostic,roleDiagnostic,loadDiagnostic} from './backtests.mjs';
const format=n=>Number.isFinite(n)?n.toFixed(2):'Not available';
const ROLE_LABELS={all_eligible:'All eligible receivers',above_average_role:'Above-average role',role_ahead_of_results:'Opportunity ahead of results'};

function ErrorComparison({rows,unit}){
 const max=Math.max(1,...rows.flatMap(r=>[r.baseline,r.challenger]).filter(Number.isFinite))*1.1;
 return <figure className="backtest-chart"><figcaption>Prediction error in {unit} · lower is better · bars start at zero</figcaption>{rows.map(r=><div key={r.label}><h3>{r.label}</h3>{[['Baseline',r.baseline,false],['Experimental',r.challenger,true]].map(([label,value,experimental])=><div className="backtest-bar-row" key={label}><span>{label}</span><div className="backtest-bar-track" aria-hidden="true"><div className={`backtest-bar${experimental?' experimental':''}`} style={{width:Number.isFinite(value)?`${value/max*100}%`:'0%'}}/></div><strong>{format(value)}</strong></div>)}</div>)}</figure>;
}
function SnapshotState({state,onRetry}){
 return state.busy?<p role="status">Loading published backtest…</p>:<div className="empty-state"><p role="alert">{state.error}</p><button type="button" onClick={onRetry}>Retry backtest</button></div>;
}
export function BacktestView({onResults}){
 const [refresh,setRefresh]=useState(0),[game,setGame]=useState({busy:true}),[role,setRole]=useState({busy:true});
 useEffect(()=>{let alive=true;setGame({busy:true});setRole({busy:true});const read=async(file,parse,set)=>{try{const data=await loadDiagnostic(file,parse);if(alive)set({data});}catch(e){if(alive)set({error:e.message});}};read('football_game_validation.json',gameDiagnostic,setGame);read('football_role_validation.json',roleDiagnostic,setRole);return()=>{alive=false;};},[refresh]);
 const retry=()=>setRefresh(n=>n+1),g=game.data,r=role.data,all=r?.rows.find(x=>x.name==='all_eligible');
 return <div className="backtest-view">
  <section className="panel"><div className="section-heading"><div><span className="eyebrow">HISTORICAL VALIDATION</span><h2>Football backtests</h2></div><span className="source-pill">Separate from live results</span></div><p>Did an earlier-data model predict later games well? These walk-forward tests help evaluate football methods. They do not validate today’s GOING rating or establish profitable bets.</p><div className="backtest-actions"><button type="button" onClick={onResults}>View saved-price $100 results</button><button type="button" onClick={retry} disabled={game.busy||role.busy}>Refresh backtests</button></div></section>
  <section className="panel"><div className="section-heading"><div><span className="eyebrow">NFL · GAME MODELS</span><h2>Week-ahead score test</h2></div>{g?.seasons&&<span className="source-pill">{g.seasons[0]}–{g.seasons[1]} archive</span>}</div>{g?<><strong className="backtest-stat">{g.games.toLocaleString()} games</strong><p>Baseline versus opponent-adjusted experimental model. RMSE measures typical prediction error, with larger misses penalized more.</p><ErrorComparison rows={g.rows} unit="points (RMSE)"/><div className="backtest-conclusion">{g.rows.map(row=><p key={row.label}><strong>{row.label}:</strong> {row.improvementRange?`95% week-cluster interval for error reduction: ${format(row.improvementRange[0])} to ${format(row.improvementRange[1])} points. ${row.improvementRange[0]>0?'The interval favors the experimental model.':'The interval does not establish an improvement.'}`:'No uncertainty interval published.'}</p>)}<p>No production model is promoted by this view.</p></div><details><summary>Method and limits</summary><p>Each season/week is tested using earlier weeks only, after at least 64 training games. Training games must start at least 12 hours before the test week’s first kickoff. The opponent experiment uses current-season scores and prior-season observations at 35% weight, with a ridge prior; this is a separate historical comparison, not today’s 80/20 policy.</p><p>Latest revised nflverse data, not an archive of what was published at each historic kickoff. This is a score diagnostic across the displayed seasons, not a 2026-only result or an untouched confirmation set. Historical lines/prices are absent, so betting ROI is unavailable.</p>{g.generatedAt&&<p>Snapshot generated {new Date(g.generatedAt).toLocaleString()}.</p>}<a href="../data/football_game_validation.json">Published game summary</a></details></>:<SnapshotState state={game} onRetry={retry}/>}</section>
  <section className="panel"><div className="section-heading"><div><span className="eyebrow">NFL · RECEIVING ROLE</span><h2>Next-game opportunity test</h2></div>{r&&<span className="source-pill">{r.season} season</span>}</div>{r?<><strong className="backtest-stat">{all.games.toLocaleString()} player-games</strong><p>Does an opportunity-ahead-of-results adjustment improve next-game receiving-yard predictions? MAE is the average absolute miss in yards.</p><ErrorComparison rows={[{label:'All eligible receivers',baseline:all.baseline,challenger:all.challenger}]} unit="yards (MAE)"/><p className="backtest-conclusion">{Number.isFinite(all.baseline)&&Number.isFinite(all.challenger)?all.challenger>=all.baseline?'The experimental adjustment did not improve average error. It remains out of the production model.':'Lower historical error alone is insufficient for promotion; the adjustment remains experimental.':'No complete paired error comparison is available.'}</p><div className="table-wrap"><table><caption>Declared role groups overlap; do not add their sample sizes.</caption><thead><tr><th>Role group</th><th>Player-games</th><th>Baseline MAE</th><th>Adjusted MAE</th></tr></thead><tbody>{r.rows.map(row=><tr key={row.name}><td>{ROLE_LABELS[row.name]}</td><td>{row.games}</td><td>{format(row.baseline)}</td><td>{format(row.challenger)}</td></tr>)}</tbody></table></div><details><summary>Method and limits</summary><p>Weekly role flags use earlier games. The adjustment learns only from already graded earlier weeks, with a 100-player-game zero prior. Actual participation selects the evaluated player-games retrospectively; this cannot simulate a historical availability decision.</p><p>Revised source data, correlated player-games and no historical prices. Opportunity and box-score result stay separate; this test does not prove a bounce-back bet or validate the /100 rating.</p><a href="../data/football_role_validation.json">Published role summary</a></details></>:<SnapshotState state={role} onRetry={retry}/>}</section>
  <section className="panel"><h2>What this can validate</h2><p>Use historical error to reject weak model ideas and identify candidates for a new, preregistered future test. Use immutable pregame records to evaluate real recommendations, calibration and saved-price ROI. Neither automatically raises ratings.</p><p>The new GOING /100 rating needs its own frozen v2 outcomes. No NCAA historical backtest is published yet; NCAA prospective game results remain in Results. Missing historical injury timestamps, routes and decision-time quotes cannot be reconstructed from current data.</p></section>
 </div>;
}
