import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {summarize,displayLine} from './metrics.mjs';
import {loadJournal} from './load-journal.mjs';
import {recordedEvidence} from './evidence.mjs';
import './style.css';

const money=n=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD'}):'—';
const pct=n=>Number.isFinite(n)?`${(100*n).toFixed(1)}%`:'—';
const GROUP_LABELS={best_model:'GOING qualified plays',best_value:'Price-qualified value',all_projection:'Primary-line projection audit',all_model:'All price-model checks',alerts:'Alert-qualified picks'};

function ProfitChart({series,maxDrawdown}){
 const points=series||[],width=760,height=220,pad=24,values=points.map(p=>p.cumulative),minimum=Math.min(0,...values),maximum=Math.max(0,...values),span=Math.max(100,maximum-minimum),x=i=>pad+(i/Math.max(1,points.length-1))*(width-pad*2),y=value=>pad+(maximum-value)/span*(height-pad*2),line=points.map((p,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(p.cumulative).toFixed(1)}`).join(' '),zeroY=y(0);
 return <section className="panel performance"><div className="section-heading"><div><span className="eyebrow">CHRONOLOGICAL RECORD</span><h2>Hypothetical result over time</h2></div><span className="source-pill">$100 flat stakes</span></div><p>Every step uses the price and projection frozen before kickoff. This is model evaluation, not a betting account.</p>{points.length>1?<><div className="chart-summary"><span><small>Ending result</small><strong>{money(points.at(-1).cumulative)}</strong></span><span><small>Largest drawdown</small><strong>{money(maxDrawdown)}</strong></span><span><small>Settled selections</small><strong>{points.length-1}</strong></span></div><div className="profit-chart"><svg role="img" aria-label="Cumulative hypothetical result" viewBox={`0 0 ${width} ${height}`}><line className="zero-line" x1={pad} x2={width-pad} y1={zeroY} y2={zeroY}/><path className="profit-line" d={line}/>{points.map((p,i)=><circle key={`${p.prediction_id||'start'}-${i}`} className="profit-point" cx={x(i)} cy={y(p.cumulative)} r="3"><title>{i===0?'Start':`${new Date(p.at).toLocaleDateString()}: ${money(p.cumulative)}`}</title></circle>)}</svg></div></>:<div className="empty-state"><strong>The prospective record is starting now.</strong><p>No settled selections exist for this view yet. GOING will never backfill past winners.</p></div>}</section>;
}

function TrackerDashboard({records,meta,privateMode=false}){
 const groups=privateMode?['all_model','all_projection','best_model','best_value','alerts']:['best_model','best_value','all_projection'];
 const [group,setGroup]=useState(groups[0]),[sport,setSport]=useState('all'),[days,setDays]=useState('all'),[query,setQuery]=useState('');
 const scoped=useMemo(()=>{const since=days==='all'?0:Date.now()-Number(days)*86400000,predictions=records.filter(r=>r.kind==='prediction'&&Date.parse(r.observed_at)>=since&&(sport==='all'||(r.payload?.sport||'nfl')===sport)),ids=new Set(predictions.map(r=>r.id));return records.filter(r=>r.kind==='prediction'?ids.has(r.id):ids.has(r.payload?.prediction_id));},[records,sport,days]);
 const stats=useMemo(()=>summarize(scoped,group),[scoped,group]);
 const picks=stats.predictions.filter(p=>!query||`${p.player||''} ${p.home||''} ${p.away||''} ${p.market||''} ${p.book||''}`.toLowerCase().includes(query.toLowerCase()));
 const open=picks.filter(p=>Date.parse(p.kickoff)>Date.now()).sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)||b.probability-a.probability),lastRun=meta?.generated_at?new Date(meta.generated_at):null;
 return <>
  <section className="tracker-hero"><div><span className="eyebrow">{privateMode?'PRIVATE JOURNAL':'PUBLIC · AUTOMATIC · AUDITABLE'}</span><h2>{privateMode?'My private records':'GOING performance tracker'}</h2><p>{privateMode?'Your owner-scoped journal. It never changes the public model record.':'What GOING published before kickoff, what actually happened, and how the model is performing—visible without an account.'}</p></div><div className="tracker-health"><span className={`health-dot ${lastRun&&Date.now()-lastRun<36*3600000?'fresh':'stale'}`}></span><div><strong>{lastRun?`Updated ${lastRun.toLocaleString()}`:'Waiting for first scheduled snapshot'}</strong><small>{meta?.latest_run?`${meta.latest_run.eligible??0} eligible now · ${meta.latest_run.captured} newly frozen · ${meta.latest_run.settled} settled`:privateMode?'Loaded on demand':'GitHub-hosted scheduled tracker'}</small></div></div></section>
  <section className="controls tracker-controls"><label>Board<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(value=><option key={value} value={value}>{GROUP_LABELS[value]}</option>)}</select></label><label>Sport<select value={sport} onChange={e=>setSport(e.target.value)}><option value="all">NFL + NCAA</option><option value="nfl">NFL</option><option value="ncaa">NCAA</option></select></label><label>Review window<select value={days} onChange={e=>setDays(e.target.value)}><option value="all">Complete record</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label></section>
  <section className="tiles"><article><small>Hypothetical $100 result</small><strong>{stats.bets?money(stats.profit):'—'}</strong><span>{stats.bets} settled selections · {stats.games} games</span></article><article><small>Return on tracked stakes</small><strong>{stats.bets?pct(stats.profit/(stats.bets*100)):'—'}</strong><span>Refunds return the original stake</span></article><article><small>Tracking coverage</small><strong>{stats.coverage.completed?pct(stats.coverage.settledShare):'—'}</strong><span>{stats.coverage.settled} settled · {stats.coverage.awaiting} awaiting · {stats.coverage.upcoming} upcoming</span></article><article><small>Current tracked slate</small><strong>{open.length}</strong><span>Prospective selections frozen before kickoff</span></article></section>
  <ProfitChart series={stats.series} maxDrawdown={stats.maxDrawdown}/>
 <section className="panel"><div className="section-heading"><div><span className="eyebrow">DECLARED BEFORE KICKOFF</span><h2>Results by market</h2></div><span className="source-pill">{GROUP_LABELS[group]}</span></div><p>Each exact contract and side counts once from its first prospective observation. Alternate lines do not masquerade as independent picks, and multiple selections from one game are not independent evidence.</p><div className="table-wrap"><table><thead><tr><th>Market</th><th>Settled</th><th>Games</th><th>Profit</th><th>Return</th></tr></thead><tbody>{stats.markets.map(row=><tr key={row.label}><td>{row.label}</td><td>{row.bets}</td><td>{row.games}</td><td>{money(row.profit)}</td><td>{pct(row.roi)}</td></tr>)}</tbody></table></div>{!stats.markets.length&&<p>No settled markets in this view yet.</p>}</section>
  <section className="panel"><div className="section-heading"><div><span className="eyebrow">RECEIPTS</span><h2>Completed tracked plays</h2></div><span className="source-pill">Latest 60</span></div><div className="cards result-cards">{stats.graded.slice(-60).reverse().map(p=><article key={p.prediction_id} className={`result-card ${p.status}`}><span className="result-status">{p.status.toUpperCase()}</span><h3>{p.player||`${p.away} at ${p.home}`}</h3><p>{p.market} · {p.side} {displayLine(p)} · {p.book}</p><strong>{money(p.profit)}</strong><small>Recorded chance {pct(p.probability)} · Frozen {new Date(p.prediction_observed_at).toLocaleString()}<br/>Actual: {p.actual??'confirmed final result'}</small></article>)}</div>{!stats.graded.length&&<div className="empty-state"><strong>No completed selections yet.</strong><p>The record begins with genuinely prospective selections; previous games are not reconstructed after the result.</p></div>}</section>
  <section className="panel"><div className="section-heading"><div><span className="eyebrow">CURRENT RECORD</span><h2>Tracked selections</h2></div><span className="source-pill">{picks.length} records</span></div><input className="tracker-search" aria-label="Search tracked selections" placeholder="Search player, team, market or book" value={query} onChange={e=>setQuery(e.target.value)}/><div className="cards tracked-cards">{picks.slice(0,80).map(p=><article key={p.id}><span className="badge">{Date.parse(p.kickoff)>Date.now()?'UPCOMING':'AWAITING / COMPLETE'}</span><h3>{p.player||`${p.away} at ${p.home}`}</h3><p>{p.market} · {p.side} {displayLine(p)} · {p.book}</p><p><strong>{pct(p.probability)}</strong> recorded estimate · {p.american>0?'+':''}{p.american} price</p><small>Frozen {new Date(p.observed_at).toLocaleString()} · Kickoff {new Date(p.kickoff).toLocaleString()}</small><details><summary>Show saved evidence</summary>{recordedEvidence(p).map((line,i)=><p key={i}>{line}</p>)}</details></article>)}</div>{!picks.length&&<div className="empty-state"><strong>No selections in this view.</strong><p>Choose another board or wait for the next scheduled slate capture.</p></div>}</section>
  {!privateMode&&<section className="panel methodology"><h2>What this tracker does</h2><p>Predictions are frozen by the scheduled GitHub pipeline before kickoff. Later runs attach published final results without changing the original line, price or estimate. GOING reports empty samples and losing periods as-is.</p><p><strong>Qualified plays:</strong> {meta?.methodology?.best_model||'Declared GOING recommendations.'}<br/><strong>Value:</strong> {meta?.methodology?.best_value||'Independently price-qualified selections.'}<br/><strong>Projection audit:</strong> {meta?.methodology?.all_projection||'One representative line per market and side.'}</p><small>{meta?.limitations||'No retroactive results, invented outcomes or silently changed predictions.'}</small></section>}
 </>;
}

function App(){
 const [snapshot,setSnapshot]=useState(null),[publicBusy,setPublicBusy]=useState(true),[publicError,setPublicError]=useState('');
 const [client,setClient]=useState(null),[session,setSession]=useState(null),[configured,setConfigured]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[privateBusy,setPrivateBusy]=useState(false),[privateError,setPrivateError]=useState(''),[privateRecords,setPrivateRecords]=useState([]),[privateLoaded,setPrivateLoaded]=useState(false);
 async function loadPublic(){setPublicBusy(true);setPublicError('');try{let body,lastError;const stamp=Date.now(),urls=[new URL(`../api/snapshot?file=public_tracker.json&t=${stamp}`,document.baseURI),new URL(`../data/public_tracker.json?t=${stamp}`,document.baseURI)];for(const url of urls){try{const response=await fetch(url);if(!response.ok)throw Error(`HTTP ${response.status}`);body=await response.json();break;}catch(error){lastError=error;}}if(!body)throw Error(`The public tracker snapshot is not available yet${lastError?.message?` (${lastError.message})`:''}.`);if(body.schema_version!==1||!Array.isArray(body.records))throw Error('The public tracker snapshot is invalid.');setSnapshot(body);}catch(error){setPublicError(error.message);}finally{setPublicBusy(false);}}
 useEffect(()=>{loadPublic();let alive=true,subscription;fetch('/api/validation-config').then(r=>r.ok?r.json():null).then(async config=>{if(!alive)return;setConfigured(!!config?.url&&!!config?.publishableKey);if(config?.url&&config?.publishableKey){const c=createClient(config.url,config.publishableKey);setClient(c);const {data}=await c.auth.getSession();if(alive)setSession(data.session);subscription=c.auth.onAuthStateChange((_,next)=>{if(alive){setSession(next);setPrivateLoaded(false);setPrivateRecords([]);}}).data.subscription;}}).catch(()=>alive&&setConfigured(false));return()=>{alive=false;subscription?.unsubscribe();};},[]);
 async function login(event){event.preventDefault();setPrivateBusy(true);setPrivateError('');const {error}=await client.auth.signInWithPassword({email,password});setPassword('');if(error)setPrivateError(error.message);setPrivateBusy(false);}
 async function loadPrivate(){if(!client||!session||privateBusy)return;setPrivateBusy(true);setPrivateError('');try{const result=await loadJournal(client,session.user.id,new Date(Date.now()-365*86400000).toISOString(),new Date().toISOString());setPrivateRecords(result.records);setPrivateLoaded(true);}catch(error){setPrivateError(error.message?.includes('statement timeout')?'The optional private journal timed out. The public GOING tracker above is unaffected.':error.message);}finally{setPrivateBusy(false);}}
 return <main><nav><a href="/">GOING</a><a href="/long/?mode=betting">Football board ↗</a><a href="/yard/">Baseball ↗</a><a href="#private-journal">Personal journal</a></nav><header><span className="eyebrow">PUBLIC PERFORMANCE / FROZEN BEFORE KICKOFF</span><h1>Every call.<br/>Every outcome.</h1><p>A public, chronological record of what GOING showed before games began—built for accountability, not screenshots of winners.</p><button onClick={loadPublic} disabled={publicBusy}>{publicBusy?'Refreshing…':'Refresh public tracker'}</button></header>
 {publicError&&<p role="alert" className="error">{publicError}</p>}
 {snapshot?<TrackerDashboard records={snapshot.records} meta={snapshot}/>:!publicBusy&&!publicError?<div className="empty-state"><strong>Waiting for the first public snapshot.</strong></div>:null}
 <details id="private-journal" className="panel private-journal"><summary><strong>Personal journal</strong><span>Optional · private · loaded only when requested</span></summary><p>This area is for your own accepted bets and private records. It is separate from the public model tracker and never blocks the page above.</p>{privateError&&<p role="alert" className="error">{privateError}</p>}{!session?(configured===null?<p>Checking the optional private connection…</p>:!configured?<p>Private account storage is not configured. The public tracker remains fully available.</p>:<form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={privateBusy}>Sign in</button></form>):<><div className="private-actions"><button onClick={loadPrivate} disabled={privateBusy}>{privateBusy?'Loading…':privateLoaded?'Refresh my journal':'Load my journal'}</button><button onClick={()=>client.auth.signOut()}>Sign out</button></div>{privateLoaded&&<TrackerDashboard key="private" records={privateRecords} meta={{generated_at:new Date().toISOString()}} privateMode/>}</>}</details>
 <footer>Public tracking is prospective and automatic. Probability is not confidence; short samples do not prove an edge. Existing ParlayAPI and data-source costs are separate from this free GitHub-hosted tracker.</footer></main>;
}

createRoot(document.getElementById('root')).render(<App/>);
