import React,{useEffect,useMemo,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {summarize} from './metrics.mjs';
import {loadJournal} from './load-journal.mjs';
import './style.css';
const money=n=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD'}):'—';
const pct=n=>Number.isFinite(n)?(100*n).toFixed(1)+'%':'—';
function App(){
 const [group,setGroup]=useState('all_model');
 const [client,setClient]=useState(null),[session,setSession]=useState(null),[status,setStatus]=useState(null),[records,setRecords]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[sport,setSport]=useState('all'),[days,setDays]=useState(30),[query,setQuery]=useState(''),[actual,setActual]=useState([]),[form,setForm]=useState({prediction:'',stake:'',odds:'',at:''});
 useEffect(()=>{let alive=true,unsubscribe;Promise.all([fetch('/api/validation-config').then(r=>r.ok?r.json():null),fetch('/api/snapshot?file=topdown_status.json').then(r=>r.ok?r.json():null)]).then(async([config,scan])=>{if(!alive)return;setStatus(scan);setConfigured(!!config?.url&&!!config?.publishableKey);if(config?.url&&config?.publishableKey){const c=createClient(config.url,config.publishableKey);setClient(c);const {data}=await c.auth.getSession();if(alive)setSession(data.session);unsubscribe=c.auth.onAuthStateChange((_,s)=>{if(alive){setSession(s);setRecords([]);setActual([]);}}).data.subscription;}}).catch(()=>{if(alive){setConfigured(false);setError('Connection check failed. Retry when the service is available.');}});return()=>{alive=false;unsubscribe?.unsubscribe();};},[]);
 const refreshVersion=useRef(0),refreshBusy=useRef(false);
 async function refresh(){if(!client||!session||refreshBusy.current)return;refreshBusy.current=true;const version=refreshVersion.current;setBusy(true);setError('');try{
 const latest=await client.from('market_journal').select('payload').eq('owner_id',session.user.id).eq('kind','run').order('observed_at',{ascending:false}).limit(1);
 if(latest.error)throw latest.error;if(version!==refreshVersion.current)return;if(latest.data[0])setStatus(latest.data[0].payload);
 const result=await loadJournal(client,session.user.id,new Date(Date.now()-days*86400000).toISOString(),new Date().toISOString());
 if(version!==refreshVersion.current)return;setRecords(result.records);setActual(result.actual);
 }catch(e){if(version===refreshVersion.current){setError(e.message?.includes('statement timeout')?'The database took too long to respond. Scanner status is shown separately; try Refresh journal again.':e.message);setRecords([]);setActual([]);}}finally{refreshBusy.current=false;setBusy(false);}}

 useEffect(()=>{if(!session)return;setRecords([]);setActual([]);let retry;const start=()=>{if(refreshBusy.current){retry=setTimeout(start,100);return;}refresh();};start();const timer=setInterval(refresh,60000);return()=>{clearInterval(timer);clearTimeout(retry);refreshVersion.current++;};},[session,days]);
 const stats=useMemo(()=>summarize(records.filter(r=>sport==='all'||(r.payload.sport||'nfl')===sport),group),[records,sport,group]);const picks=stats.predictions.filter(p=>!query||`${p.player||''} ${p.home} ${p.away} ${p.market} ${p.book}`.toLowerCase().includes(query.toLowerCase()));
 async function login(e){e.preventDefault();setBusy(true);setError('');const {error}=await client.auth.signInWithPassword({email,password});setPassword('');if(error)setError(error.message);setBusy(false);}
 async function recordBet(e){e.preventDefault();const p=stats.predictions.find(p=>p.id===form.prediction),at=Date.parse(form.at);if(!p||!(Number(form.stake)>0)||!(Number(form.odds)>1)||!Number.isFinite(at)||at>=Date.parse(p.kickoff)){setError('Choose a prediction, positive stake, valid decimal payout and a time before kickoff.');return;}setBusy(true);const {error}=await client.from('placed_bets').insert({prediction_id:p.id,owner_id:session.user.id,placed_at:new Date(at).toISOString(),stake:Number(form.stake),accepted_decimal:Number(form.odds),book:p.book});setBusy(false);if(error)setError(error.message);else{setForm({prediction:'',stake:'',odds:'',at:''});refresh();}}
 const statusStale=!status?.observed_at||Date.now()-Date.parse(status.observed_at)>5*60000;
 return <main><nav><a href="/">GOING</a><a href="/long/?mode=betting">Football board ↗</a><a href="/yard/">Baseball ↗</a></nav><header><span className="eyebrow">MARKET RESEARCH / PRIVATE TRACKING</span><h1>Make the claim.<br/>Keep the receipt.</h1><p>Compare prices first. Record the decision before kickoff. Check the price near kickoff and the real result afterward.</p></header>
 <section className="panel"><h2>Scanner readiness</h2><p>NFL: {status?.sports?.nfl?.research_predictions??0} checks / {status?.sports?.nfl?.actionable_predictions??0} eligible. NCAA: {status?.sports?.ncaa?.research_predictions??0} checks / {status?.sports?.ncaa?.actionable_predictions??0} eligible.</p><p>NCAA tracks game lines only in the final 90 minutes. Availability is not independently verified; NFL still requires official inactive lists.</p><p className="badge">{statusStale?'No recent scan confirmed':'Latest scan recorded'} · {status?.actionable_predictions||0} eligible price checks at that scan</p><p>Reference books observed: {status?.reference_books?.join(', ')||'none verified'}. Pinnacle plus a supporting reference is preferred. Pinnacle alone requires an extra {(100*(status?.single_source_extra_hurdle??.005)).toFixed(1)} percentage points of estimated return. Official NFL.com inactive lists are checked automatically in the final 90 minutes. Both teams must be confirmed. A missing report at 75 minutes before kickoff triggers a Discord warning.</p><p>{status?.observed_at?'Last scan: '+new Date(status.observed_at).toLocaleString():'No scanner observation has been published.'} {status?.supabase?.status==='not_configured'?'Private database delivery is not configured.':''}</p><small>Official-report feed: {status?.inactive_feed?.state==='verified'?'both lists confirmed':status?.inactive_feed?.state==='awaiting_official_reports'?'waiting for complete official lists':'waiting for the final window'}.<br/>{status?.timestamp_desyncs??0} checks blocked by prices more than 60 seconds apart; {status?.pending_inactives??0} checks waiting for the final 90 minutes.<br/>Missing prices, unverified reports or future-dated quotes block alerts. A price difference does not reveal who bet or why. Displayed arbitrage still depends on accepted stakes and matching settlement rules.</small></section>
 {error&&<p role="alert" className="error">{error}</p>}
 {!session?<section className="panel"><h2>Your prediction journal</h2>{configured===null?<p>Checking the private connection…</p>:!configured?<p>Supabase is not connected. The database migration and scanner are included in the repository; private results will appear after the project and owner account are configured. No demo returns or invented records are shown.</p>:<form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button></form>}</section>:<>
 <section className="controls"><label>Tracking group<select aria-label="Tracking group" value={group} onChange={e=>setGroup(e.target.value)}><option value="all_model">All price-model checks</option><option value="all_projection">All historical-model plays</option><option value="best_model">Best Plays: win chance</option><option value="best_value">Best Plays: value</option><option value="alerts">Alert-qualified picks</option></select></label><label>Sport<select aria-label="Sport" value={sport} onChange={e=>setSport(e.target.value)}><option value="all">NFL + NCAA</option><option value="nfl">NFL</option><option value="ncaa">NCAA</option></select></label><label>Review window<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>365 days</option></select></label><button onClick={refresh} disabled={busy}>{busy?'Loading…':'Refresh journal'}</button><button onClick={()=>client.auth.signOut()}>Sign out</button><button onClick={()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({records,actual},null,2)],{type:'application/json'}));a.href=url;a.download='going-private-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export this window</button></section>
 <p>Automatic hypothetical tracking. Each selection is frozen before kickoff and counted once per group. All-check groups include opposing sides and blocked ideas; their results are a diagnostic, not a recommended betting portfolio. Best Plays tracking began when this feature was enabled; earlier winners are never added retrospectively.</p>
 <section className="tiles"><article><small>Hypothetical $100 per selected bet</small><strong>{stats.bets?money(stats.profit):'—'}</strong><span>{stats.bets} graded selections / {stats.games} games</span></article><article><small>Return on those hypothetical stakes</small><strong>{stats.bets?pct(stats.profit/(stats.bets*100)):'—'}</strong><span>Refunded bets return $0 profit</span></article><article><small>Validation status</small><strong>{stats.bets?'Early recorded results':'Not yet validated'}</strong><span>No automated claim of proven edge</span></article></section>
 <section className="panel"><h2>Results by payout range</h2><p>Decimal payout includes your original stake: 2.00 returns $200 for a winning $100 bet. Each contract and side counts once, using its first recorded observation in this group. Multiple picks in one game are not independent evidence.</p><div className="table-wrap"><table><thead><tr><th>Payout range</th><th>Bets</th><th>Games</th><th>Profit / $100 stakes</th><th>Return</th><th>Probability error</th></tr></thead><tbody>{stats.bands.map(b=><tr key={b.band}><td>{b.band}</td><td>{b.bets}</td><td>{b.games}</td><td>{money(b.profit)}</td><td>{pct(b.roi)}</td><td>{b.brier?.toFixed(3)??'—'}</td></tr>)}</tbody></table></div>{!stats.bets&&<p>No qualifying graded selections in this window.</p>}<small>Probability error measures how far forecasts were from the outcome; lower is better. Returns and errors can bounce around sharply across a few games.</small></section>
 <section className="panel"><h2>Completed tracked plays</h2><p>Confirmed final scores are checked every two minutes while the PC is running. Player props wait for published player statistics. These results use hypothetical $100 stakes.</p><div className="cards">{stats.graded.slice(-60).reverse().map(p=><article key={p.prediction_id}><b>{p.player||p.away+' at '+p.home}</b><small>{(p.sport||'nfl').toUpperCase()}</small><p>{p.market} · {p.side} {p.line??''} · {p.book}</p><strong>{p.status.toUpperCase()} · {money(p.profit)}</strong><p>Recorded chance {pct(p.probability)} · {new Date(p.observed_at).toLocaleString()}</p></article>)}</div>{!stats.graded.length&&<p>No confirmed results for this group yet. Picks are saved automatically before kickoff.</p>}</section>
 <section className="panel"><h2>Did you beat the later price?</h2><p>A price from the same contract within ten minutes of kickoff is a useful check beyond one win or loss. Beating a well-informed later market repeatedly can support an edge claim; it does not prove one, and this feed may miss the actual last quote.</p>{stats.graded.filter(p=>p.priceMove!=null).slice(0,15).map(p=><p key={p.id}>{p.player||p.away+' at '+p.home} · {p.market} {p.side}: {pct(p.priceMove)} return advantage versus the recorded later reference price.</p>)}{!stats.graded.some(p=>p.priceMove!=null)&&<p>Near-kickoff comparisons are currently displayed for alert-qualified picks only; research win/loss tracking is independent.</p>}</section>
 <section className="panel"><h2>Decisions and blocked checks</h2><p>Includes the latest 100 checks. Results above use all eligible decisions in the selected window.</p><input aria-label="Search decisions" placeholder="Player, team, market or book" value={query} onChange={e=>setQuery(e.target.value)}/><div className="cards">{picks.slice(0,60).map(p=><article key={p.id}><span className="badge">{p.actionable?'Eligible price check':'Research only'}</span><h3>{p.player||p.away+' at '+p.home}</h3><small>{(p.sport||'nfl').toUpperCase()}{p.sport==='ncaa'?' · Availability not independently verified':''}</small><p>{p.market} · {p.side} {p.line??''} · {p.book}</p><p>Price-derived chance {pct(p.raw_probability)} → after policy discount {pct(p.probability)}. These are estimates, not known true chances.</p><p>Estimated return over many identical bets: {pct(p.ev)}. Suggested size: {money(p.proposed_stake)}.</p><small>{p.single_source?'Pinnacle-only estimate · ':''}{p.timestamp_delta_seconds!=null?'Price time difference: '+p.timestamp_delta_seconds.toFixed(0)+' seconds · ':''}{p.ev_threshold!=null?'Required repeat return: '+pct(p.ev_threshold)+' · ':''}{p.reasons.join(' · ')||'All configured checks passed.'}<br/>{new Date(p.observed_at).toLocaleString()}</small></article>)}</div>{!picks.length&&<p>No matching recorded checks.</p>}</section>
 <section className="panel"><h2>Record a bet you actually placed</h2><p>This records your accepted price and stake. It does not send a wager.</p><form onSubmit={recordBet}><label>Prediction<select required value={form.prediction} onChange={e=>setForm({...form,prediction:e.target.value})}><option value="">Choose a logged prediction</option>{picks.slice(0,200).map(p=><option key={p.id} value={p.id}>{p.player||p.away+' at '+p.home} · {p.side} {p.line} · {p.book} · {p.observed_at}</option>)}</select></label><label>Stake ($)<input type="number" min="0.01" step="0.01" required value={form.stake} onChange={e=>setForm({...form,stake:e.target.value})}/></label><label>Accepted decimal payout<input type="number" min="1.001" step="0.001" required value={form.odds} onChange={e=>setForm({...form,odds:e.target.value})}/></label><label>Time placed (your local time)<input type="datetime-local" required value={form.at} onChange={e=>setForm({...form,at:e.target.value})}/></label><button disabled={busy}>Record accepted bet</button></form><p>{actual.length} actual bets recorded in this window. Hypothetical $100 returns above are kept separate.</p></section>
 </>}
 <footer>Quarter-sized bankroll formula, capped at 1% per idea. Early team estimates lean heavily toward league averages. Policy discounts and cutoffs are disclosed rules, not earned confidence percentages.</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
