import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {summarize} from './metrics.mjs';
import './style.css';
const money=n=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD'}):'—';
const pct=n=>Number.isFinite(n)?(100*n).toFixed(1)+'%':'—';
function App(){
 const [client,setClient]=useState(null),[session,setSession]=useState(null),[status,setStatus]=useState(null),[records,setRecords]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[days,setDays]=useState(30),[query,setQuery]=useState(''),[actual,setActual]=useState([]),[form,setForm]=useState({prediction:'',stake:'',odds:'',at:''});
 useEffect(()=>{let alive=true,unsubscribe;Promise.all([fetch('/api/validation-config').then(r=>r.ok?r.json():null),fetch('/api/snapshot?file=topdown_status.json').then(r=>r.ok?r.json():null)]).then(async([config,scan])=>{if(!alive)return;setStatus(scan);setConfigured(!!config?.url&&!!config?.publishableKey);if(config?.url&&config?.publishableKey){const c=createClient(config.url,config.publishableKey);setClient(c);const {data}=await c.auth.getSession();if(alive)setSession(data.session);unsubscribe=c.auth.onAuthStateChange((_,s)=>{if(alive){setSession(s);setRecords([]);setActual([]);}}).data.subscription;}}).catch(()=>{if(alive){setConfigured(false);setError('Connection check failed. Retry when the service is available.');}});return()=>{alive=false;unsubscribe?.unsubscribe();};},[]);
 async function refresh(){if(!client||!session)return;setBusy(true);setError('');try{const latest=await client.from('market_journal').select('payload').eq('kind','run').order('observed_at',{ascending:false}).limit(1);if(latest.error)throw latest.error;if(latest.data[0])setStatus(latest.data[0].payload);const since=new Date(Date.now()-days*86400000).toISOString();let all=[];for(let offset=0;offset<20000;offset+=1000){const {data,error}=await client.from('market_journal').select('id,kind,observed_at,payload').in('kind',['prediction','settlement','closing']).gte('observed_at',since).order('observed_at',{ascending:false}).order('id').range(offset,offset+999);if(error)throw error;all.push(...data);if(data.length<1000)break;if(offset===19000)throw Error('More than 20,000 records in this window. Select fewer days; partial results will not be scored.');}const bets=await client.from('placed_bets').select('*').gte('placed_at',since).order('placed_at',{ascending:false}).limit(1000);if(bets.error)throw bets.error;if(bets.data.length===1000)throw Error('Too many placed bets in this window; choose fewer days.');setRecords(all);setActual(bets.data);}catch(e){setError(e.message);setRecords([]);setActual([]);}finally{setBusy(false);}}
 useEffect(()=>{if(!session)return;refresh();const timer=setInterval(refresh,60000);return()=>clearInterval(timer);},[session,days]);
 const stats=useMemo(()=>summarize(records),[records]);const picks=stats.predictions.filter(p=>!query||`${p.player||''} ${p.home} ${p.away} ${p.market} ${p.book}`.toLowerCase().includes(query.toLowerCase()));
 async function login(e){e.preventDefault();setBusy(true);setError('');const {error}=await client.auth.signInWithPassword({email,password});setPassword('');if(error)setError(error.message);setBusy(false);}
 async function recordBet(e){e.preventDefault();const p=stats.predictions.find(p=>p.id===form.prediction),at=Date.parse(form.at);if(!p||!(Number(form.stake)>0)||!(Number(form.odds)>1)||!Number.isFinite(at)||at>=Date.parse(p.kickoff)){setError('Choose a prediction, positive stake, valid decimal payout and a time before kickoff.');return;}setBusy(true);const {error}=await client.from('placed_bets').insert({prediction_id:p.id,owner_id:session.user.id,placed_at:new Date(at).toISOString(),stake:Number(form.stake),accepted_decimal:Number(form.odds),book:p.book});setBusy(false);if(error)setError(error.message);else{setForm({prediction:'',stake:'',odds:'',at:''});refresh();}}
 const statusStale=!status?.observed_at||Date.now()-Date.parse(status.observed_at)>5*60000;
 return <main><nav><a href="/">GOING</a><a href="/long/?mode=betting">Football board ↗</a><a href="/yard/">Baseball ↗</a></nav><header><span className="eyebrow">MARKET RESEARCH / PRIVATE TRACKING</span><h1>Make the claim.<br/>Keep the receipt.</h1><p>Compare prices first. Record the decision before kickoff. Check the price near kickoff and the real result afterward.</p></header>
 <section className="panel"><h2>Scanner readiness</h2><p className="badge">{statusStale?'No recent scan confirmed':'Latest scan recorded'} · {status?.actionable_predictions||0} eligible price checks at that scan</p><p>Reference books observed: {status?.reference_books?.join(', ')||'none verified'}. Two designated books with fresh prices are required. Official inactive reports must be verified for both teams during the final 90 minutes.</p><p>{status?.observed_at?'Last scan: '+new Date(status.observed_at).toLocaleString():'No scanner observation has been published.'} {status?.supabase?.status==='not_configured'?'Private database delivery is not configured.':''}</p><small>Missing prices, unverified reports or future-dated quotes block alerts. A price difference does not reveal who bet or why. Displayed arbitrage still depends on accepted stakes and matching settlement rules.</small></section>
 {error&&<p role="alert" className="error">{error}</p>}
 {!session?<section className="panel"><h2>Your prediction journal</h2>{configured===null?<p>Checking the private connection…</p>:!configured?<p>Supabase is not connected. The database migration and scanner are included in the repository; private results will appear after the project and owner account are configured. No demo returns or invented records are shown.</p>:<form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button></form>}</section>:<>
 <section className="controls"><label>Review window<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>365 days</option></select></label><button onClick={refresh} disabled={busy}>{busy?'Loading…':'Refresh journal'}</button><button onClick={()=>client.auth.signOut()}>Sign out</button><button onClick={()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({records,actual},null,2)],{type:'application/json'}));a.href=url;a.download='going-private-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export this window</button></section>
 <section className="tiles"><article><small>Hypothetical $100 per selected bet</small><strong>{stats.bets?money(stats.profit):'—'}</strong><span>{stats.bets} graded selections / {stats.games} games</span></article><article><small>Return on those hypothetical stakes</small><strong>{stats.bets?pct(stats.profit/(stats.bets*100)):'—'}</strong><span>Refunded bets return $0 profit</span></article><article><small>Validation status</small><strong>{stats.bets?'Early recorded results':'Not yet validated'}</strong><span>No automated claim of proven edge</span></article></section>
 <section className="panel"><h2>Results by payout range</h2><p>Decimal payout includes your original stake: 2.00 returns $200 for a winning $100 bet. Each contract and side counts once, using its first eligible observation. Multiple picks in one game are not independent evidence.</p><div className="table-wrap"><table><thead><tr><th>Payout range</th><th>Bets</th><th>Games</th><th>Profit / $100 stakes</th><th>Return</th><th>Probability error</th></tr></thead><tbody>{stats.bands.map(b=><tr key={b.band}><td>{b.band}</td><td>{b.bets}</td><td>{b.games}</td><td>{money(b.profit)}</td><td>{pct(b.roi)}</td><td>{b.brier?.toFixed(3)??'—'}</td></tr>)}</tbody></table></div>{!stats.bets&&<p>No qualifying graded selections in this window.</p>}<small>Probability error measures how far forecasts were from the outcome; lower is better. Returns and errors can bounce around sharply across a few games.</small></section>
 <section className="panel"><h2>Did you beat the later price?</h2><p>A price from the same contract within ten minutes of kickoff is a useful check beyond one win or loss. Beating a well-informed later market repeatedly can support an edge claim; it does not prove one, and this feed may miss the actual last quote.</p>{stats.graded.filter(p=>p.priceMove!=null).slice(0,15).map(p=><p key={p.id}>{p.player||p.away+' at '+p.home} · {p.market} {p.side}: {pct(p.priceMove)} return advantage versus the recorded later reference price.</p>)}{!stats.graded.some(p=>p.priceMove!=null)&&<p>No matched near-kickoff observations yet.</p>}</section>
 <section className="panel"><h2>Decisions and blocked checks</h2><input aria-label="Search decisions" placeholder="Player, team, market or book" value={query} onChange={e=>setQuery(e.target.value)}/><div className="cards">{picks.slice(0,60).map(p=><article key={p.id}><span className="badge">{p.actionable?'Eligible price check':'Research only'}</span><h3>{p.player||p.away+' at '+p.home}</h3><p>{p.market} · {p.side} {p.line??''} · {p.book}</p><p>Price-derived chance {pct(p.raw_probability)} → after policy discount {pct(p.probability)}. These are estimates, not known true chances.</p><p>Estimated return over many identical bets: {pct(p.ev)}. Suggested size: {money(p.proposed_stake)}.</p><small>{p.reasons.join(' · ')||'All configured checks passed.'}<br/>{new Date(p.observed_at).toLocaleString()}</small></article>)}</div>{!picks.length&&<p>No matching recorded checks.</p>}</section>
 <section className="panel"><h2>Record a bet you actually placed</h2><p>This records your accepted price and stake. It does not send a wager.</p><form onSubmit={recordBet}><label>Prediction<select required value={form.prediction} onChange={e=>setForm({...form,prediction:e.target.value})}><option value="">Choose a logged prediction</option>{picks.slice(0,200).map(p=><option key={p.id} value={p.id}>{p.player||p.away+' at '+p.home} · {p.side} {p.line} · {p.book} · {p.observed_at}</option>)}</select></label><label>Stake ($)<input type="number" min="0.01" step="0.01" required value={form.stake} onChange={e=>setForm({...form,stake:e.target.value})}/></label><label>Accepted decimal payout<input type="number" min="1.001" step="0.001" required value={form.odds} onChange={e=>setForm({...form,odds:e.target.value})}/></label><label>Time placed (your local time)<input type="datetime-local" required value={form.at} onChange={e=>setForm({...form,at:e.target.value})}/></label><button disabled={busy}>Record accepted bet</button></form><p>{actual.length} actual bets recorded in this window. Hypothetical $100 returns above are kept separate.</p></section>
 </>}
 <footer>Quarter-sized bankroll formula, capped at 1% per idea. Early team estimates lean heavily toward league averages. Policy discounts and cutoffs are disclosed rules, not earned confidence percentages.</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
