"""Write data/dfs_correlations.json (public, derived from public nflverse box scores) from the committed ledger: measured within-player and cross-player correlations for the DFS simulator."""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def build():
    ledger = json.loads((REPO / 'research' / 'trend-intelligence' / 'ledger.json').read_text(encoding='utf-8'))
    ex = ledger.get('experiments', ledger)
    r8, r9 = (ex['P3-8'].get('result') or ex['P3-8']), (ex['P3-9'].get('result') or ex['P3-9'])
    within = {pos: {'components': v['components'], 'matrix': v['within_player_correlation_v2']} for pos, v in r8['positions'].items()}
    roles = r9['role_correlations_dev_2021_2023']
    counts = r9['pair_counts']
    pairs = {}
    for a, row in roles.items():
        for b, value in row.items():
            if a < b and value is not None and counts[a][b] >= 300:
                pairs[f'{a}~{b}'] = {'r': value, 'n': counts[a][b]}
    return {'schema': 'dfs-correlations-v1', 'description': 'Normal-score correlations of next-game core DraftKings points (modelled components plus yardage bonuses), measured on 2021-2023 regular-season games; validated on 2024-2025 by stack-total calibration (experiment P3-9). Roles are assigned before the game by pre-game targets (WR/TE) and carries (RB).',
            'roles': ['QB', 'RB1', 'WR1', 'WR2', 'WR3', 'TE1'], 'within_player': within, 'cross_player': pairs, 'headline_pairs': r9['headline_pairs'],
            'provenance': {'experiments': ['P3-8', 'P3-9'], 'spec_sha256': {k: ex[k]['spec_sha256'] for k in ('P3-8', 'P3-9')}, 'development_seasons': [2021, 2022, 2023], 'validation': [2024, 2025]},
            'limits': ['not a prediction of contest value: no salary, ownership or field data were available', 'defence/special teams are not modelled', 'role pairs not listed had fewer than 300 team-games']}


if __name__ == '__main__':
    out = REPO / 'data' / 'dfs_correlations.json'
    built = build()
    out.write_text(json.dumps(built, indent=1) + '\n', encoding='utf-8')
    # the browser reads a static script so no extra fetch is needed; the file is generated and must not be edited by hand
    js = REPO / 'shared' / 'dfs-correlations.js'
    js.write_text('// Generated by scripts/trend_research/dfs_export.py from data/dfs_correlations.json - do not edit.\n(function(root){root.GoingDfsCorrelations=' + json.dumps(built, separators=(',', ':'))
                  + ';})(globalThis);\nif(typeof module!==\'undefined\')module.exports=globalThis.GoingDfsCorrelations;\n', encoding='utf-8')
    print('wrote', out, js)
