'use strict';
// No provider/network or retrospective --at switch. Tests call captureAt with fixtures.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const {rank,familyKey,expectedValue}=require('../../shared/ranking-policies.cjs');
const {canonicalJSON,hashPayload,readRecords,appendRecord}=require('../../shared/ranking-journal.cjs');
const {storeSnapshot,materialize,verifyCompletePools}=require('../../shared/ranking-snapshot.cjs');
const {settleRow}=require('../../shared/ranking-settlement.cjs');
const {verifyPreserved}=require('./preservation.cjs');
const INPUTS=['history','nfl_betting','ncaa_lines','football_context','season_learning','injury_context','players','football_game_validation','football_role_validation','data'];
const ASSETS=['going-score','football-opportunity','football-injuries','football-dfs','football-slate','score-tracker'];
const POLICY_FUNCTIONS=['rankBestPlays','opportunityPool','filterBestPlays','opportunityIdentity','bestDayRows','bestPriceCandidates','signalCandidates','footballWeek','footballDate'];
const GENERATOR_FUNCTIONS=['propsFromRealData','gamesFromRealData','gamesFromParlay','attachProjection','buildProfileIndex','normalizeBetName','resolveTeamName','canonicalNflTeam','americanToDecimal','normalCDF','poissonCDF','lognormalCDF','manualModel','propProbabilities','normalMarket','gameQuotes','computePropRow','evPercent','quoteState','activeGameQuote','currentGameMarket','currentWeekProp','footballTrust','signalEvent','signalReference','signalFlags','signalMedian'];
// Git checkout CRLF conversion is not a model/input change. Hash UTF-8 text with
// CRLF -> LF ONLY; preserve all other whitespace and every value for provenance.
const sha=b=>crypto.createHash('sha256').update(b.toString().replace(/\r\n/g,'\n'),'utf8').digest('hex');
const ET=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
function slotAt(at){const p=Object.fromEntries(ET.formatToParts(new Date(at)).map(x=>[x.type,x.value]));return {date:p.year+'-'+p.month+'-'+p.day,hour:Number(p.hour),minute:Number(p.minute)};}
const clone=x=>JSON.parse(JSON.stringify(x));
function picked(row){const out={};for(const k of ['kind','sport','event','kickoff','home','away','profileId','player','team','opp','market','side','line','book','odds','dec','prob','push','ev','n','profileDate','updatedAt','canonicalContract','modelFamily','projMean','projSd'])out[k]=row[k]??null;out.flags=(row.flags||[]).map(f=>({id:f.id??null,historicalOnly:!!f.historicalOnly}));const se=row.seasonEvidence??row.gameSeasonEvidence??{};out.evidence={seasonPolicy:se.policy??se.method??null,currentGames:se.current_games??null,priorGames:se.prior_games??null,homeCurrentGames:se.home_current_games??null,awayCurrentGames:se.away_current_games??null,injuryStatus:row.injury?.status??null,injuryStale:row.injury?.stale??null,roleObservedAt:row.roleEvidence?.last_game??null,reference:row.reference??null};return clone(out);}
function inputVersions(root,at){const versions={},values={};for(const name of INPUTS){const raw=fs.readFileSync(path.join(root,'data',name+'.json'));const d=JSON.parse(raw);const generatedAt=d.generated_at??d.generatedAt??d.betting?.generated_at??null;if(generatedAt&&(!Number.isFinite(Date.parse(generatedAt))||Date.parse(generatedAt)>Date.parse(at)))throw Error('Nondecision-time input: '+name);versions[name+'.json']={sha256:sha(raw),generatedAt};values[name]=d;}return {versions,values};}
function openSource(root,at,{url='http://localhost/',storedView=null}={}){const {JSDOM,VirtualConsole}=require('jsdom'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),dom=new JSDOM(html,{url,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()}),w=dom.window,D=w.Date;w.Date=class extends D{constructor(...a){super(...(a.length?a:[Date.parse(at)]));}static now(){return Date.parse(at);}};if(storedView!==null)w.localStorage.setItem('goinglong.betting.view.v1',JSON.stringify(storedView));w.fetch=()=>Promise.reject(Error('Research network disabled'));w.requestAnimationFrame=fn=>w.setTimeout(fn,0);w.HTMLElement.prototype.scrollIntoView=function(){};const context=dom.getInternalVMContext(),sourceHashes={'index.html':sha(html)};
 try{for(const asset of ASSETS){const raw=fs.readFileSync(path.join(root,'shared',asset+'.js'));sourceHashes['shared/'+asset+'.js']=sha(raw);vm.runInContext(raw.toString(),context);}for(const script of w.document.querySelectorAll('script:not([src])'))vm.runInContext(script.textContent.replace(/\nboot\(\);/,'\n'),context);const codeHashes={policy:sha(vm.runInContext('['+POLICY_FUNCTIONS.join(',')+'].map(fn=>fn.toString()).join("\\n")',context)+sourceHashes['shared/football-opportunity.js']+sourceHashes['shared/football-slate.js']),generator:sha(vm.runInContext('['+GENERATOR_FUNCTIONS.join(',')+'].map(fn=>fn.toString()).join("\\n")',context)+sourceHashes['shared/football-injuries.js'])};return {dom,w,context,sourceHashes,codeHashes};}catch(e){dom.window.close();throw e;}}
function exclusion(c,now,week){const reasons=[];if(!['nfl','ncaa'].includes(c.sport)||!['game','prop'].includes(c.kind)||(c.sport==='ncaa'&&c.kind==='prop'))reasons.push('unsupported_sport_type');const date=Number.isFinite(Date.parse(c.kickoff))?slotAt(c.kickoff).date:null;if(!date||date<week.start||date>week.last)reasons.push('outside_current_week');if(!Number.isFinite(Date.parse(c.kickoff))||Date.parse(c.kickoff)<=now)reasons.push('started_or_invalid');const age=now-Date.parse(c.updatedAt);if(!Number.isFinite(age)||age<0||age>86400000)reasons.push('quote_over_24_hours_or_invalid');if(!Number.isFinite(c.prob)||c.prob<=0||c.prob>=1||!Number.isFinite(c.n)||c.n<5)reasons.push('model_probability_or_sample_unavailable');if((c.flags||[]).some(f=>f.id==='check'&&!f.historicalOnly))reasons.push('blocking_model_check');return reasons;}
function normalizeScope(ordered){const policies={};for(const method of ['champion','ev','family-diversified-ev']){const xs=rank(ordered,method);policies[method]={ranks:xs.map(x=>x.id),top3:xs.slice(0,3).map(x=>x.id),top10:xs.slice(0,10).map(x=>x.id)};}return policies;}
async function captureAt(root,at,{revision='fixture',experiment=null,allowFixture=false}={}){
 if(!Number.isFinite(Date.parse(at)))throw Error('Invalid decision time');const now=Date.parse(at),{versions,values}=inputVersions(root,at),source=openSource(root,at),{w,context}=source;
 try{if(experiment){if(source.codeHashes.policy!==experiment.policyCodeHash||source.codeHashes.generator!==experiment.generatorCodeHash)throw Error('Frozen experiment source changed: create a new version; never overwrite v1');if(sha(fs.readFileSync(path.join(root,'shared/ranking-policies.cjs')))!==experiment.challengersSourceHash)throw Error('Frozen C1/C2 implementation changed');if(now<Date.parse(experiment.startedAt))throw Error('Cannot collect before preregistration');}else if(!allowFixture)throw Error('Registered experiment required');
 w.fixture=values;await vm.runInContext('(async()=>{const d=fixture;BET.config=d.data?.betting||{};S.pipeline=d.data;BET.history=d.history?.betting;S.history=d.history;BET.nflData=d.nfl_betting;BET.ncaaData=d.ncaa_lines;BET.context=d.football_context;BET.learning=d.season_learning;BET.injuryLearning=d.injury_context;BET.roster=d.players;BET.gameValidation=d.football_game_validation;BET.roleValidation=d.football_role_validation;BET.injuryContext=GoingFootballInjuries.createContext(BET.roster,BET.history?.profiles,Date.now(),BET.injuryLearning);BET.liveLoaded={nfl:true,ncaa:true};BET.props=await propsFromRealData();BET.games=gamesFromRealData();globalThis.modelRows=await signalCandidates();const prices=bestPriceCandidates();globalThis.allRows=[...modelRows.flatMap(c=>c.offers?.length?c.offers:[c]),...prices];globalThis.allQuotes=[...(SIGNAL.allQuotes||[]),...prices];})()',context);
 const raw=vm.runInContext('allRows',context),week=clone(vm.runInContext('footballWeek(Date.now())',context)),date=slotAt(at).date;
 // Row IDs use source order to disambiguate even identical offers. No generated UI UUIDs.
 const rows=raw.map((c,index)=>{const p=picked(c),reasons=exclusion(c,now,week);let family=null;try{family=familyKey(c);}catch{}return {...p,id:'r'+index,frozenAt:at,slateDate:Number.isFinite(Date.parse(c.kickoff))?slotAt(c.kickoff).date:null,family,quoteAgeSeconds:Number.isFinite(Date.parse(c.updatedAt))?(now-Date.parse(c.updatedAt))/1000:null,quoteFresh5m:Number.isFinite(Date.parse(c.updatedAt))&&now-Date.parse(c.updatedAt)>=0&&now-Date.parse(c.updatedAt)<=300000,eligibility:{preDedupEligible:!reasons.length,excluded:reasons,championRank:null,c1Rank:null,c2Rank:null}};});
 // Keep the source row index through production's copies, filter and exact-contract dedup.
 for(let i=0;i<raw.length;i++)raw[i].researchId=rows[i].id;
 const scopes=[];for(const [sport,kind] of [['nfl','all'],['nfl','prop'],['nfl','game'],['ncaa','game']]){w.sport=sport;w.kind=kind;const result=vm.runInContext('rankBestPlays(allRows,allQuotes,sport,kind,Date.now(),"all")',context),rankedRaw=result.chance;w.ranked=rankedRaw;w.opts={query:'',focus:'all',sort:'going',value:false,book:'all',excludeAlt:true,minOdds:-500,day:'slate',event:'all',now};const filtered=vm.runInContext('filterBestPlays(ranked,opts)',context);const ordered=clone(filtered).map(x=>({...x,id:x.researchId}));if(ordered.some(x=>!x.id))throw Error('Production row identity lost');
 const primary=sport==='nfl'&&kind==='all'||sport==='ncaa';const beforeIds=new Set(rankedRaw.map(x=>x.researchId)),afterIds=new Set(ordered.map(x=>x.id));if(primary)for(const row of rows.filter(x=>x.sport===sport)){if(!beforeIds.has(row.id)&&!row.eligibility.excluded.length)row.eligibility.excluded.push('canonical_contract_duplicate');else if(beforeIds.has(row.id)&&!afterIds.has(row.id)){const original=rankedRaw.find(x=>x.researchId===row.id);row.eligibility.excluded.push(original?.kind==='prop'&&original.isAltLine?'alternate_prop_hidden':'minimum_odds_filter');}row.eligibility.eligible=afterIds.has(row.id);}
 for(const scope of ['week','today','today-settleable']){const selected=scope==='week'?ordered:ordered.filter(x=>slotAt(x.kickoff).date===date&&(scope!=='today-settleable'||['spread','total','moneyline','pass_yds','rush_yds','rec_yds','receptions','pass_tds','rush_tds','rec_tds','atd'].includes(x.market))),policies=normalizeScope(selected);scopes.push({sport,kind,scope,slateDate:scope==='week'?null:date,policies});if(primary&&scope==='week')for(const [method,field] of [['champion','championRank'],['ev','c1Rank'],['family-diversified-ev','c2Rank']])policies[method].ranks.forEach((id,i)=>rows[Number(id.slice(1))].eligibility[field]=i+1);}
 }
 // Quotes discarded before opportunityPool are retained with the production reason.
 const preCandidateExclusions=clone(vm.runInContext('BET.props.map(p=>{const r=computePropRow(p);const reasons=[];if(!currentWeekProp(p))reasons.push("outside_current_week");if(p.dfs||p.manual||p.source==="manual")reasons.push("manual_or_dfs");const state=quoteState(p);if(state)reasons.push(state);if(!r.dec||!finiteNumber(r.ev)||!p.profileId)reasons.push("projection_or_price_unavailable");if(Date.parse(p.profileDate)>=Date.now())reasons.push("profile_not_before_decision");if(!p.eventTeams?.[0]||!p.eventTeams?.[1])reasons.push("team_identity_unresolved");return {player:p.player??null,profileId:p.profileId??null,eventId:p.eventId??null,home:p.eventTeams?.[0]??null,away:p.eventTeams?.[1]??null,kickoff:p.kickoff??null,market:p.market??null,line:p.line??null,book:p.book??null,overOdds:p.overOdds??null,underOdds:p.underOdds??null,updatedAt:p.updatedAt??null,reasons};}).filter(p=>p.reasons.length)',context));
 const gameExclusions=clone(vm.runInContext('BET.games.filter(g=>g.source==="manual"||!activeGameQuote(g)||!inCurrentFootballWeek(g.kickoff)).map(g=>({sport:g.sport,home:g.homeCode||g.home,away:g.awayCode||g.away,kickoff:g.kickoff,book:g.book??null,updatedAt:g.updatedAt??null,reason:g.source==="manual"?"manual":!inCurrentFootballWeek(g.kickoff)?"outside_current_week":"inactive_game_quote",spread:g.spread??null,total:g.total??null,mlHome:g.mlHome??null,mlAway:g.mlAway??null}))',context));
 const snapshot={schemaVersion:1,experiment:experiment?.id??'fixture',registrationHash:experiment?hashPayload(experiment):null,decisionTime:at,sourceRevision:revision,sourceHashes:source.sourceHashes,inputVersions:versions,codeHashes:source.codeHashes,week,slateDate:date,rows,preCandidateExclusions,gameExclusions,scopes,sourceNote:'Complete renderBestPlays input pool plus pre-generation exclusions; unsupported/unparsed raw markets remain reproducible in pinned Git input blobs, not invented candidates.'};
 // Re-read inputs: a concurrent refresh cannot silently mix two vintages.
 for(const [name,v] of Object.entries(versions))if(sha(fs.readFileSync(path.join(root,'data',name)))!==v.sha256)throw Error('Input changed during capture: '+name);
 for(const [name,h] of Object.entries(source.sourceHashes))if(sha(fs.readFileSync(path.join(root,name)))!==h)throw Error('Source changed during capture: '+name);
 return snapshot;
 }finally{source.dom.window.close();}
}
function slotKey(experiment,at,mode){const p=slotAt(at);if(mode==='scheduled'){if(![2,8,10,12,14,17,20,22].includes(p.hour)||p.minute>15)throw Error('Outside registered scheduled capture window; no retrospective catchup');return experiment+'|'+p.date+'|'+String(p.hour).padStart(2,'0');}if(mode==='manual')return experiment+'|manual|'+at;throw Error('Invalid capture mode');}
const SETTLEABLE=new Set(['spread','total','moneyline','pass_yds','rush_yds','rec_yds','receptions','pass_tds','rush_tds','rec_tds','atd']);
function validateSnapshot(s){
 if(s?.schemaVersion!==1||!Array.isArray(s.rows)||!Array.isArray(s.scopes)||!s.inputVersions||!s.sourceHashes||!Number.isFinite(Date.parse(s.decisionTime)))throw Error('Invalid snapshot');
 const ids=new Map(s.rows.map(r=>[r.id,r]));if(ids.size!==s.rows.length)throw Error('Duplicate snapshot row IDs');
 for(const row of s.rows){
  if(row.frozenAt!==s.decisionTime)throw Error('Freeze time mismatch');
  if(row.sport==='ncaa'&&row.kind==='prop')throw Error('Unsupported NCAA props');
  if(!row.eligibility||!Array.isArray(row.eligibility.excluded))throw Error('Missing auditable eligibility');
  if(row.eligibility.eligible){
   const quote=Date.parse(row.updatedAt),decision=Date.parse(s.decisionTime);
   if(!(quote<=decision&&decision-quote<=86400000&&decision<Date.parse(row.kickoff)))throw Error('Eligible row chronology');
   const ev=expectedValue(row),decimal=row.odds<0?1+100/-row.odds:1+row.odds/100;
   if(!Number.isFinite(row.odds)||Math.abs(row.odds)<100||row.odds< -500||Math.abs(decimal-row.dec)>1e-12||Math.abs(ev-row.ev)>1e-12)throw Error('Frozen price/return mismatch');
   if(row.eligibility.excluded.length||row.family!==familyKey(row)||row.prob<=0||row.prob>=1||row.n<5)throw Error('Frozen eligibility/family mismatch');
  }
 }
 const scopeKeys=new Set();
 for(const scope of s.scopes){
  const key=[scope.sport,scope.kind,scope.scope].join('|');if(scopeKeys.has(key))throw Error('Duplicate scope');scopeKeys.add(key);
  const championIds=scope.policies?.champion?.ranks;if(!Array.isArray(championIds))throw Error('Missing Champion ranks');
  const champion=championIds.map(id=>ids.get(id));if(champion.some(r=>!r))throw Error('Invalid complete policy ranks');
  const expected=s.rows.filter(r=>r.eligibility.eligible&&r.sport===scope.sport&&(scope.kind==='all'||r.kind===scope.kind)&&(scope.scope==='week'||r.slateDate===s.slateDate&&(scope.scope!=='today-settleable'||SETTLEABLE.has(r.market))));
  if(canonicalJSON([...championIds].sort())!==canonicalJSON(expected.map(r=>r.id).sort()))throw Error('Incomplete eligible Champion pool');
  for(let i=1;i<champion.length;i++)if(champion[i].prob>champion[i-1].prob||champion[i].prob===champion[i-1].prob&&champion[i].ev>champion[i-1].ev)throw Error('Champion ordering mismatch');
  for(const method of ['champion','ev','family-diversified-ev']){
   const p=scope.policies[method];if(!p||!Array.isArray(p.ranks)||new Set(p.ranks).size!==p.ranks.length||p.ranks.some(id=>!ids.has(id)))throw Error('Invalid complete policy ranks');
   if(canonicalJSON(p.top3)!==canonicalJSON(p.ranks.slice(0,3))||canonicalJSON(p.top10)!==canonicalJSON(p.ranks.slice(0,10)))throw Error('Top-N mismatch');
   if(canonicalJSON(rank(champion,method,{decisionTime:s.decisionTime,evaluationMode:'historical'}).map(r=>r.id))!==canonicalJSON(p.ranks))throw Error('Frozen Challenger ranks mismatch');
  }
  if(scope.scope==='week'&&(scope.kind==='all'||scope.sport==='ncaa'))for(const [method,field] of [['champion','championRank'],['ev','c1Rank'],['family-diversified-ev','c2Rank']])scope.policies[method].ranks.forEach((id,i)=>{if(ids.get(id).eligibility[field]!==i+1)throw Error('Frozen per-row rank mismatch');});
 }
 for(const [sport,kind] of [['nfl','all'],['nfl','prop'],['nfl','game'],['ncaa','game']])for(const scope of ['week','today','today-settleable'])if(!scopeKeys.has([sport,kind,scope].join('|')))throw Error('Missing complete scope');
 return true;
}
function invalidateSnapshot(directory,{snapshotHash,reason,evidence,observedAt=new Date().toISOString()}){
 const records=readRecords(directory);if(!records.some(r=>r.kind==='snapshot'&&r.hash===snapshotHash))throw Error('Invalidation target must be a preserved snapshot');
 if(typeof reason!=='string'||reason.trim().length<10||typeof evidence!=='string'||evidence.trim().length<10)throw Error('Invalidation requires a specific reason and evidence reference');
 return appendRecord(directory,{kind:'invalidation',key:'invalidation|'+snapshotHash+'|'+hashPayload({reason,evidence}),observedAt,payload:{snapshotHash,reason,evidence}});
}
function appendSettlements(journal,root,at){const raw=fs.readFileSync(path.join(root,'data/results.json')),results=JSON.parse(raw),revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),records=readRecords(journal),existing=new Map(records.map(r=>[r.key,r])),added=[];
 for(const snapshot of records.filter(r=>r.kind==='snapshot')){const frozen=materialize(snapshot,records);validateSnapshot(frozen);const outcomes=[];for(const row of frozen.rows.filter(r=>r.eligibility.eligible)){const grade=settleRow(row,results,{observedAt:at,sourceRevision:revision,sourceHash:sha(raw)});if(grade.status!=='unresolved')outcomes.push(grade);}
 if(!outcomes.length)continue;const key='settlement|'+snapshot.hash+'|'+sha(raw);if(existing.has(key))continue;const prior=records.filter(r=>r.kind==='settlement'&&r.payload.snapshotHash===snapshot.hash);const first=new Map();for(const r of prior)for(const o of r.payload.outcomes||[])if(!first.has(o.predictionId))first.set(o.predictionId,o);const novel=outcomes.filter(o=>!first.has(o.predictionId)||first.get(o.predictionId).status!==o.status||first.get(o.predictionId).actual!==o.actual);if(!novel.length)continue;
 const conflicts=novel.filter(o=>first.has(o.predictionId)).map(o=>o.predictionId);const record=appendRecord(journal,{kind:'settlement',key,observedAt:at,payload:{snapshotHash:snapshot.hash,sourceRevision:revision,sourceHash:sha(raw),outcomes:novel,conflicts,interpretation:'Statistical published-result grading; not executable wager/book-void settlement. Conflicts require explicit auditable invalidation/review, never automatic replacement.'}});added.push(record);}
 return added;
}
async function main(){const [action,sourceArg,journalArg,mode='scheduled']=process.argv.slice(2);if(!['capture','verify','settle'].includes(action)||!sourceArg||!journalArg)throw Error('Usage: node research/today-ranking/collect.cjs capture|verify|settle SOURCE_CHECKOUT JOURNAL_DIR [scheduled|manual]');const root=path.resolve(sourceArg),journalRoot=path.resolve(journalArg);if(action==='capture'&&!fs.existsSync(journalRoot))fs.mkdirSync(journalRoot,{recursive:true});const preservation=verifyPreserved(journalRoot),segments=fs.readdirSync(journalRoot).sort();if(segments.some(n=>!/^\d{4}-\d{2}-\d{2}$/.test(n)||!fs.statSync(path.join(journalRoot,n)).isDirectory()))throw Error('Unexpected journal root entry');for(const segment of segments)verifyCompletePools(readRecords(path.join(journalRoot,segment)));if(action==='verify'){let total=0,snapshots=0;for(const segment of segments){const records=readRecords(path.join(journalRoot,segment));for(const r of records.filter(r=>r.kind==='snapshot')){validateSnapshot(materialize(r,records));snapshots++;}total+=records.length;}console.log(JSON.stringify({records:total,snapshots,segments:segments.length,preservation}));return;}
 const at=new Date().toISOString();execFileSync('git',['diff','--exit-code','HEAD','--'],{cwd:root,stdio:'pipe'});const revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),experiment=JSON.parse(fs.readFileSync(path.join(root,'research/today-ranking/experiment-'+(/today-ranking-v1/.test(journalRoot)?'v1':/today-ranking-v2/.test(journalRoot)?'v2':'v3')+'.json')));if(action==='settle'){let count=0;for(const segment of segments)count+=appendSettlements(path.join(journalRoot,segment),root,at).length;console.log(JSON.stringify({settlementsAdded:count}));return;}if(Date.parse(at)>Date.parse(experiment.collectionEndsAt))throw Error('Preregistered collection ended; evaluate or register a new experiment');const journal=path.join(journalRoot,slotAt(at).date),key=slotKey(experiment.id,at,mode),records=readRecords(journal);if(records.some(r=>r.key===key)){console.log(JSON.stringify({status:'existing_frozen_slot',key}));return;}
 const snapshot=await captureAt(root,at,{revision,experiment});snapshot.trigger={mode,slot:slotAt(at),primaryWindow:mode==='scheduled'&&slotAt(at).hour===8&&slotAt(at).minute<=15};validateSnapshot(snapshot);const record=storeSnapshot(journal,snapshot,key);const stored=materialize(record,readRecords(journal));validateSnapshot(stored);if(canonicalJSON(stored)!==canonicalJSON(snapshot))throw Error('Stored snapshot differs from complete captured pool');console.log(JSON.stringify({status:'frozen',key,hash:record.hash,rows:snapshot.rows.length,eligible:snapshot.rows.filter(r=>r.eligibility.eligible).length,primaryWindow:snapshot.trigger.primaryWindow}));}
module.exports={captureAt,validateSnapshot,slotAt,slotKey,openSource,inputVersions,normalizeScope,appendSettlements,exclusion,invalidateSnapshot,textHash:sha};if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1;});
