(function(root){
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function key(c){const t=Date.parse(c.kickoff),home=String(c.home||'').trim().toUpperCase(),away=String(c.away||'').trim().toUpperCase();return Number.isFinite(t)&&home&&away?[c.sport,t,away,home].join('|'):'';}
function group(chance,value){const groups=new Map();for(const [rows,kind] of [[chance,'model'],[value,'price']])for(const c of rows){const id=key(c);if(!id)continue;if(!groups.has(id))groups.set(id,{key:id,game:c,model:[],price:[]});groups.get(id)[kind].push(c);}return [...groups.values()];}
function render(groups,{label,confidence,score,teamLabel,selected=new Set(),open=new Set(),limit=12}={}){
return groups.slice(0,limit).map(g=>{const lead=g.model[0]||g.price[0],observed=Date.parse(lead.updatedAt),priceAge=Number.isFinite(observed)?Math.max(0,Date.now()-observed):null,priceNote=priceAge===null?'Price timestamp unavailable; verify availability.':priceAge>300000?'Saved price, over five minutes old; check the current line.':'Recently observed price; verify before betting.',e=confidence(lead),s=score?.(lead),why=(lead.flags||[]).find(f=>f.id!=='check')?.why||`${lead.n||'Unknown'} recorded games support the estimate; open the evidence to check sample, availability and price.`,stamp=new Date(g.game.kickoff).toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'});
return `<article class="slate-game"><header><h3>${esc(teamLabel(g.game.away,g.game.sport))} @ ${esc(teamLabel(g.game.home,g.game.sport))}</h3><small>${esc(stamp)} ET</small></header><p class="slate-count">${g.model.length} model-ranked research ${g.model.length===1?'candidate':'candidates'} · ${g.price.length} fresh price comparisons</p><p><small>Lead candidate · not a ticket suggestion</small><strong>${esc(lead.kind==='prop'?lead.player+' · ':'')}${esc(label(lead))}</strong></p><p class="slate-evidence">Evidence: <b>${esc(e.label)}</b>${Number.isFinite(s)?` · Player GOING Score <b>${s.toFixed(1)}/100</b> (player index, not win chance)${lead.side==='Under'?' · Not an Under or exact-line score.':''}`:''}</p><p class="slate-why">${esc(why)}</p><small class="slate-price-note">${esc(priceNote)}</small><div class="slate-actions"><button data-slate-action="parlay" data-slate-game="${esc(g.key)}" aria-pressed="${selected.has(g.key)}">${selected.has(g.key)?'✓ Selected for parlay':'Select game for parlay'}</button><button data-slate-action="games" data-slate-game="${esc(g.key)}">Compare this matchup</button>${g.game.sport==='nfl'?`<button data-slate-action="score" data-slate-game="${esc(g.key)}">Player GOING Scores</button>`:''}</div><details class="slate-bets" data-slate-open="${esc(g.key)}" ${open.has(g.key)?'open':''}><summary>View bets &amp; why · ${g.model.length+g.price.length} research entries</summary><div class="slate-bets-body"></div></details></article>`;}).join('')||'<div class="bt-empty">No supported research candidates match this date and filters. Try the full football week or Games to browse available prices. No recommendation is invented.</div>';
}
root.GoingFootballSlate={key,group,render};if(typeof module!=='undefined')module.exports=root.GoingFootballSlate;
})(globalThis);
