(function(root){
'use strict';
const E=root.GoingEvidence,esc=E.esc,finite=x=>typeof x==='number'&&Number.isFinite(x),KEY='going.shared.picks.v1';let offers=new Map();
const NFL_LOGOS={ARI:['ari','Arizona Cardinals'],ATL:['atl','Atlanta Falcons'],BAL:['bal','Baltimore Ravens'],BUF:['buf','Buffalo Bills'],CAR:['car','Carolina Panthers'],CHI:['chi','Chicago Bears'],CIN:['cin','Cincinnati Bengals'],CLE:['cle','Cleveland Browns'],DAL:['dal','Dallas Cowboys'],DEN:['den','Denver Broncos'],DET:['det','Detroit Lions'],GB:['gb','Green Bay Packers'],HOU:['hou','Houston Texans'],IND:['ind','Indianapolis Colts'],JAX:['jax','Jacksonville Jaguars'],JAC:['jax','Jacksonville Jaguars'],KC:['kc','Kansas City Chiefs'],LAC:['lac','Los Angeles Chargers'],LAR:['lar','Los Angeles Rams'],LA:['lar','Los Angeles Rams'],LV:['lv','Las Vegas Raiders'],MIA:['mia','Miami Dolphins'],MIN:['min','Minnesota Vikings'],NE:['ne','New England Patriots'],NO:['no','New Orleans Saints'],NYG:['nyg','New York Giants'],NYJ:['nyj','New York Jets'],PHI:['phi','Philadelphia Eagles'],PIT:['pit','Pittsburgh Steelers'],SEA:['sea','Seattle Seahawks'],SF:['sf','San Francisco 49ers'],TB:['tb','Tampa Bay Buccaneers'],TEN:['ten','Tennessee Titans'],WAS:['wsh','Washington Commanders'],WSH:['wsh','Washington Commanders']};
function teamMarks(teams){const aliases={LA:'LAR',JAC:'JAX',WAS:'WSH'},unique=[...new Set((teams||[]).map(x=>String(x||'').toUpperCase().trim()).filter(Boolean).map(code=>aliases[code]||code))];if(!unique.length)return '';return `<span class="g-team-logos" role="group" aria-label="NFL teams">${unique.map(code=>{const match=NFL_LOGOS[code];if(!match)return '';const [slug,name]=match;return `<span class="g-team-mark" role="img" title="${esc(name)}" aria-label="${esc(name)}"><img src="https://a.espncdn.com/i/teamlogos/nfl/500/${slug}.png" alt="" aria-hidden="true" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.hidden=true"><span>${esc(code)}</span></span>`;}).join('')}</span>`;}
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[];}catch{return [];}}
function write(rows){try{localStorage.setItem(KEY,JSON.stringify(rows));}catch{}renderSlip();}
function add(row){const rows=read(),i=rows.findIndex(x=>x.id===row.id);if(i>=0)rows.splice(i,1);else rows.push({...row,label:row.player&&!String(row.label).includes(row.player)?row.player+' · '+row.label:row.label});write(rows);return i<0;}
function card(c){offers.set(c.id,c);const stale=!finite(Date.parse(c.updatedAt))||Date.now()-Date.parse(c.updatedAt)>24*3600000||Date.parse(c.kickoff)<=Date.now(),saved=read().some(x=>x.id===c.id),teams=c.kind==='game'?[c.away,c.home]:[c.team,c.team===c.home?c.away:c.home],marks=c.sport==='nfl'?teamMarks(teams):'',cheatsheet=c.sport==='nfl'&&c.cheatsheetEvidence?.length?`<details class="g-cheatsheet"><summary>Related cheatsheet context</summary><p class="g-note">Supporting GOING data for this matchup. These observations are descriptive context and are not added again to the pick’s score or probability.</p><dl class="best-evidence">${c.cheatsheetEvidence.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`:'';return `<article class="g-card best-card"><div class="g-bet-head"><div><span class="g-kicker">${esc(c.sport?.toUpperCase())} · ${esc(c.marketLabel||c.market)} · ${esc(c.qualification||'Research candidate')}</span><h3>${esc(c.player||c.label)}</h3></div><span class="g-price">${finite(c.odds)?(c.odds>0?'+':'')+c.odds:'No price'}</span></div>${marks}<strong>${esc(c.label)}</strong><p class="g-note">${esc(c.away)} @ ${esc(c.home)} · ${esc(c.book||'No matched book')} · ${stale?'Stale / unavailable quote':esc(new Date(c.updatedAt).toLocaleString())}</p><div class="g-evidence"><div class="g-stat"><span>${c.sport==='mlb'?'Projection / research strength':'Projection / probability'}</span><h3>${esc(c.projectionLabel||'Unavailable')}</h3></div><div class="g-stat"><span>Evidence confidence</span><h3>${esc(c.confidence||'Limited')}</h3></div></div><p><strong>Why</strong> · ${esc(c.why)}</p><p class="g-warning"><strong>Main risk</strong> · ${esc(c.risk)}</p><p class="g-note"><strong>Parlay fit</strong> · ${esc(c.parlay||'Compare at one book; correlation and final price need confirmation.')}</p><details><summary>Show me the data</summary>${c.chartStats?E.panel(c.chartStats):E.bet(c)}${cheatsheet}<details><summary>Sources and full evidence</summary><dl class="best-evidence">${(c.evidence||[]).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><small>${esc(c.source||'GOING published snapshot')}</small></details></details><div class="g-actions"><button data-going-pick="${esc(c.id)}" aria-pressed="${saved}" ${!finite(c.odds)||stale?'disabled':''}>${saved?'Remove pick':'Add / compare / parlay'}</button>${c.researchUrl?`<a href="${esc(c.researchUrl)}">Player research ↗</a>`:''}</div></article>`;}
function renderSlip(){if(typeof document==='undefined')return;let box=document.getElementById('goingSharedSlip');if(!box){box=document.createElement('details');box.id='goingSharedSlip';box.className='g-slip';document.body.append(box);}const rows=read();box.hidden=!rows.length;const books=new Set(rows.map(x=>String(x.book||'').toLowerCase())),events=new Set(rows.map(x=>x.event||[x.sport,x.home,x.away,x.kickoff].join('|'))),stale=rows.some(x=>!Number.isFinite(Date.parse(x.kickoff))||Date.parse(x.kickoff)<=Date.now()||!Number.isFinite(Date.parse(x.updatedAt))||Date.now()-Date.parse(x.updatedAt)>24*3600000),coherent=rows.length>=2&&books.size===1&&events.size===rows.length&&!stale;
 const decimal=x=>x>0?1+x/100:1+100/-x,product=coherent&&rows.every(x=>finite(x.odds)&&Math.abs(x.odds)>=100)?rows.reduce((v,x)=>v*decimal(x.odds),1):null;
 box.innerHTML=`<summary>${rows.length} shared ${rows.length===1?'pick':'picks'} · Compare & parlay</summary>${rows.map(r=>`<div class="g-slip-row"><div><b>${esc(r.label)}</b><small class="g-note"><br>${esc(r.sport?.toUpperCase())} · ${esc(r.book)} · ${esc(r.odds)}</small></div><button data-going-remove="${esc(r.id)}" aria-label="Remove ${esc(r.label)}">×</button></div>`).join('')}<p class="g-note">${stale?'One or more legs have started or have an old/unknown quote. Recheck them.':books.size>1?'Different books selected. Match all legs at one book before building a ticket.':events.size<rows.length?'Same-game legs: use the sportsbook’s actual combined price.':product?`Separate-game price product: ${product.toFixed(2)} decimal. Indicative only; confirm the ticket at your book.`:'Add another selection to compare.'} Joint win probability is unavailable.</p><div class="g-actions"><a href="/long/?mode=betting&tab=parlays">Parlay Lab</a><button data-going-clear>Clear picks</button></div>`;}
if(typeof document!=='undefined'){document.addEventListener('click',e=>{const p=e.target.closest('[data-going-pick]'),r=e.target.closest('[data-going-remove]');if(p){const row=offers.get(p.dataset.goingPick);if(row){const saved=add(row);p.setAttribute('aria-pressed',String(saved));p.textContent=saved?'Remove pick':'Add / compare / parlay';}}else if(r)write(read().filter(x=>x.id!==r.dataset.goingRemove));else if(e.target.closest('[data-going-clear]'))write([]);});window.addEventListener('storage',renderSlip);document.addEventListener('DOMContentLoaded',renderSlip);}
root.GoingUI={card,read,write,add,renderSlip,teamMarks};if(typeof module!=='undefined')module.exports=root.GoingUI;
})(globalThis);
