/* Approved-reference presentation only; no model/ranking/DFS state. */
(()=>{
'use strict';
const paths={home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',football:'M5 19C-1 9 10-1 20 4c5 10-5 20-15 15ZM8 16l8-8M8 10l6 6M11 7l6 6',baseball:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM5 5c6 4 6 10 0 14M19 5c-6 4-6 10 0 14',people:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM17 10a3 3 0 1 0 0-6M1 22v-3c0-7 14-7 14 0v3ZM17 13c5 0 6 3 6 7v2',bars:'M4 21v-7M11 21V7M18 21V2',search:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16ZM16 16l6 6',menu:'M3 6h18M3 12h12M3 18h18',bell:'M5 17v-7c0-8 14-8 14 0v7l2 2H3ZM9 22h6',calendar:'M5 2v5M19 2v5M2 9h20M2 5h20v17H2ZM6 13h2M11 13h2M16 13h2M6 18h2M11 18h2',market:'M2 18l6-9 6 5 7-12M17 2h4v4',game:'M3 4h18v16H3ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',file:'M5 2h10l5 5v15H5ZM14 2v6h6M8 12h8M8 17h8',book:'M12 5c-3-3-8-3-10-2v17c4-1 7 0 10 2M12 5c3-3 8-3 10-2v17c-4-1-7 0-10 2M12 5v17',layers:'M2 7 12 2l10 5-10 5ZM2 12l10 5 10-5M2 17l10 5 10-5',trophy:'M6 2h12v10c0 8-12 8-12 0ZM6 5H2v3c0 5 4 5 4 5M18 5h4v3c0 5-4 5-4 5M12 17v5M7 22h10',crown:'M2 7l4 3 6-8 6 8 4-3-3 14H5Z',more:'M4 12h.01M12 12h.01M20 12h.01',external:'M13 2h9v9M22 2 11 13M8 4H2v18h18v-6',dollar:'M12 1v22M18 5c-12-7-17 8-6 7s8 13-7 6',bolt:'M14 1 3 14h8l-1 9 11-14h-8Z',target:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10ZM12 12h.01'};
const icon=name=>`<svg class="v-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.more}"/></svg>`;
window.GoingVisual={icon};const shell=document.getElementById('going-shell');if(!shell)return;
const word=shell.querySelector('.going-wordmark');word.insertAdjacentHTML('afterbegin',icon('bars'));if(document.body.dataset.goingWorkspace!=='home')word.insertAdjacentHTML('beforeend','<small class="v-tagline">DATA. CONTEXT. BETS.</small>');
shell.querySelectorAll('.going-global-nav a').forEach((a,i)=>a.insertAdjacentHTML('afterbegin',icon(['home','football','baseball','people','bars'][i])));
const actions=document.createElement('div');actions.className='v-header-actions';actions.innerHTML=`<button type="button" data-v-search aria-label="Search Going Long">${icon('search')}</button>${document.getElementById('btDataNote')?`<button type="button" data-v-status aria-label="Open data status">${icon('bell')}</button>`:''}<details class="v-header-menu"><summary aria-label="Open site menu">${icon('menu')}</summary><nav aria-label="Site menu">${shell.querySelector('.going-global-nav').innerHTML}</nav></details>`;shell.querySelector('.going-shell-inner').append(actions);
const reveal=element=>{for(let p=element.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;};
actions.querySelector('[data-v-search]').onclick=()=>{const candidates=[document.getElementById('goingSearch'),...document.querySelectorAll('input[type=search]')];const field=candidates.find(e=>{if(!e||e.closest('[hidden]'))return false;for(let p=e;p;p=p.parentElement)if(getComputedStyle(p).display==='none')return false;return true;});if(field){reveal(field);field.scrollIntoView({block:'center'});field.focus({preventScroll:true});}else location.href='/players/';};
actions.querySelector('[data-v-status]')?.addEventListener('click',()=>{const d=document.querySelector('.g-source-status');if(!d)return;reveal(d);d.open=true;d.scrollIntoView({block:'center'});d.querySelector('summary').focus({preventScroll:true});});
shell.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=shell.querySelector('.v-header-menu');d.open=false;d.querySelector('summary').focus();}});
const bottom=document.getElementById('glNav');if(bottom)for(const b of bottom.querySelectorAll('button')){b.querySelector('.ic')?.remove();b.insertAdjacentHTML('afterbegin',icon(b.dataset.view==='betting'?'dollar':b.dataset.view==='fantasy'?'people':'external'));}
if(!bottom&&document.body.dataset.goingWorkspace==='results'){const modes=document.createElement('nav');modes.className='v-mode-nav';modes.setAttribute('aria-label','GOING modes');modes.innerHTML=`<a href="/long/?mode=betting">${icon('dollar')}Betting</a><a href="/long/?mode=fantasy">${icon('people')}Fantasy</a><a href="/">${icon('external')}Gateway</a>`;document.body.append(modes);}
const grid=document.getElementById('btTabGroup'),head=document.querySelector('.bt-head'),league=document.getElementById('btSportGroup');if(!grid||!head||!league)return;
const tools={today:['calendar','Research by game'],opportunities:['market','Lines, totals, props'],games:['game','Matchups & evidence'],dfs:['file','Projections & salaries'],cheatsheets:['book','Quick reference'],parlay:['layers','Build your ticket'],score:['trophy','Player evidence index'],jackpot:['crown','First, last & longest TD']};
for(const b of grid.querySelectorAll(':scope > button')){const [glyph,sub]=tools[b.dataset.section]||['more','Research'];b.innerHTML=`${icon(glyph)}<span class="v-tool-label">${b.textContent}<small>${sub}</small></span><span class="v-tool-chevron" aria-hidden="true">›</span>`;}
grid.querySelector('.bt-more-tools>summary').innerHTML=`${icon('more')}<span class="v-tool-label">More<small>Tools & resources</small></span><span class="v-tool-chevron" aria-hidden="true">⌄</span>`;
const hero=document.createElement('section');hero.className='v-football-hero';hero.setAttribute('aria-label','Football research overview');head.insertBefore(hero,grid);
const meta={abbeys:['ABBEYS','Current-season football. One straight-up winner per game.'],today:['TODAY','Data-backed markets, matchups and evidence for the selected slate.'],opportunities:['MARKETS','Compare available lines, totals and player markets.'],games:['GAMES','The matchup, a little clearer. Prices and evidence by game.'],dfs:['DFS','Real salaries. Your players. Two clear research objectives.'],cheatsheets:['CHEAT|SHEETS','Everything you need to investigate. Compare roles, targets, carries, and more.'],parlay:['PARLAYS','Build and edit a ticket from the games you care about.'],jackpot:['JACKPOT','First TD, Last TD and longest-touchdown research.'],research:['MORE','Tools, evidence and deeper football research.']};
// Reuse the existing team badges; never invent records or matchup values.
const scoreBoard=document.getElementById('scoreBoard');
const slateSummary=document.getElementById('bestTodaySummary');
if(slateSummary){const decorate=()=>{for(const [i,tile] of [...slateSummary.children].entries()){if(tile.dataset.visualSummary)continue;tile.insertAdjacentHTML('afterbegin',`<span class="v-summary-icon" aria-hidden="true">${icon(['football','file','target'][i])}</span>`);tile.dataset.visualSummary='true';}};new MutationObserver(decorate).observe(slateSummary,{childList:true});decorate();}
if(scoreBoard){const compact=()=>{for(const card of scoreBoard.querySelectorAll('.score-card:not([data-visual-compact])')){const actions=card.querySelector('.best-actions'),details=card.querySelector('details');if(actions&&details)details.append(actions);card.dataset.visualCompact='true';}};new MutationObserver(compact).observe(scoreBoard,{childList:true,subtree:true});compact();}
const slate=document.getElementById('bestGameSlate');
if(slate){const badges=()=>{for(const card of slate.querySelectorAll('.slate-game:not([data-visual-badges])')){const key=card.querySelector('[data-slate-game]')?.dataset.slateGame?.split('|'),title=card.querySelector('header h3');if(key?.[0]==='nfl'&&title&&typeof window.teamBadge==='function'){title.setAttribute('aria-label',title.textContent);title.innerHTML=window.teamBadge(key[2])+' <span aria-hidden="true">@</span> '+window.teamBadge(key[3]);}const actions=card.querySelector('.slate-actions'),bets=card.querySelector('.slate-bets');if(actions&&bets)bets.insertBefore(actions,bets.querySelector('.slate-bets-body'));card.dataset.visualBadges='true';}};new MutationObserver(badges).observe(slate,{childList:true,subtree:true});badges();}
const wrap=head.parentElement,sourceStatus=wrap.querySelector('.g-source-status'),globalSearch=wrap.querySelector('.going-search'),scorePanel=document.getElementById('btScorePanel');const context=document.createElement('details');context.className='v-score-context';context.hidden=true;context.innerHTML='<summary>NFL · Football tools</summary>';wrap.insertBefore(context,head);
let previous='';const update=()=>{const sport=league.querySelector('[aria-pressed=true]')?.dataset.sport||'nfl',section=grid.querySelector('button[aria-pressed=true]')?.dataset.section||'today',signature=sport+'|'+section;if(signature===previous)return;previous=signature;document.body.dataset.visualTool=section;document.body.dataset.visualLeague=sport;context.querySelector('summary').textContent=sport.toUpperCase()+' · Football tools';
if(section==='score'){hero.hidden=true;context.hidden=false;context.open=false;context.append(head);if(sourceStatus)context.append(sourceStatus);if(globalSearch)context.append(globalSearch);}else{if(head.parentElement===context){wrap.insertBefore(head,document.getElementById('btToolGroup'));if(globalSearch)wrap.insertBefore(globalSearch,scorePanel);if(sourceStatus)wrap.insertBefore(sourceStatus,globalSearch||scorePanel);}context.hidden=true;hero.hidden=false;const [title,desc]=meta[section]||meta.research;hero.innerHTML=`<small class="v-hero-kicker">${sport.toUpperCase()} · GOING LONG</small><h1>${title.includes('|')?title.split('|')[0]+'<em>'+title.split('|')[1]+'</em>':sport.toUpperCase()+' <em>'+title+'</em>'}</h1><p>${desc}</p>${section==='today'?`<div class="v-hero-features"><span>${icon('bolt')}<b>Model-driven<br>research</b></span><span>${icon('bars')}<b>Recorded<br>football data</b></span><span>${icon('target')}<b>Parlay-ready<br>markets</b></span></div>`:''}`;}
head.insertBefore(hero,section==='today'?grid:league);};new MutationObserver(update).observe(head,{subtree:true,attributes:true,attributeFilter:['aria-pressed']});update();
if(document.currentScript?.src){const reference=document.createElement('script');reference.src=new URL('reference-workspace.js',document.currentScript.src).href;document.head.append(reference);}
})();
