/* Inventory every inline stylesheet; --consolidate performs a mechanical migration. */
const fs=require('fs'),postcss=require('postcss');
const files=process.env.GOING_DESIGN_YARD?['docs/index.html']:['index.html','apps/yard/index.html','hub/index.html','shared/football-dfs.css','shared/going-score.css'];
const own=/^(background|background-color|color|border-color|border-radius|box-shadow|font-family|font-size|font-weight|text-transform|letter-spacing)$/;
const counters={};
const palette={bg:[16,24,32],surface:[25,36,47],raised:[34,49,63],border:[53,71,87],text:[241,245,249],muted:[175,191,205],accent:[98,221,189],'accent-soft':[22,61,57],blue:[117,186,255],purple:[189,164,255],amber:[244,198,117],danger:[255,146,140]};
function colorToken(hex){let h=hex.slice(1);if(h.length===3||h.length===4)h=h.split('').map(c=>c+c).join('');const rgb=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16));const key=Object.keys(palette).sort((a,b)=>palette[a].reduce((sum,v,i)=>sum+(v-rgb[i])**2,0)-palette[b].reduce((sum,v,i)=>sum+(v-rgb[i])**2,0))[0],alpha=h.length===8?parseInt(h.slice(6),16)/255:1;return alpha===1?`var(--g-${key})`:`color-mix(in srgb, var(--g-${key}) ${Math.round(alpha*100)}%, transparent)`;}
function tokenize(css){let tree;try{tree=postcss.parse(css);}catch{return css;}tree.walkDecls(d=>{if(d.prop.startsWith('--g-'))return;d.value=d.value.replace(/#[0-9a-f]{8}\b|#[0-9a-f]{6}\b|#[0-9a-f]{4}\b|#[0-9a-f]{3}\b/gi,colorToken);if(d.prop==='font-family')d.value='var(--g-font)';if(d.prop==='font-weight'&&/^\d+$/.test(d.value))d.value=Number(d.value)>=750?'var(--g-weight-display)':Number(d.value)>=600?'var(--g-weight-bold)':Number(d.value)>=500?'var(--g-weight-medium)':'var(--g-weight-normal)';if(d.prop==='border-radius'&&/^\d+(\.\d+)?px$/.test(d.value)){const n=parseFloat(d.value);d.value=n>40?'var(--g-radius-pill)':n>14?'var(--g-radius-lg)':n>9?'var(--g-radius-md)':'var(--g-radius-sm)';}if(d.prop==='box-shadow'&&d.value!=='none'&&!d.value.includes('var(--g-')){d.value=/modal|dialog|drawer|sheet|overlay|popover/.test(d.parent.selector||'')?'var(--g-shadow-modal)':'var(--g-shadow-card)';}});return tree.toString();}
function processCSS(css,file){let tree;try{tree=postcss.parse(css);}catch{return css;}const inventory=counters[file]||={rules:0,controls:0,surfaces:0,text:0,removed:0};tree.walkRules(rule=>{inventory.rules++;const selectors=rule.selectors||[],controls=selectors.every(s=>/(?:\bbutton\b|\.btn\b|\.sortchip\b|\.fbtn\b)/.test(s)&&!/[ >](?:span|small|svg|i|b)\b/.test(s));const surfaces=selectors.every(s=>/\.(?:best-card|sig-card|going-card|score-card|pl-card|sgp-card|panel|sport)\b/.test(s)&&!/[ >][.#a-z]/.test(s));if(controls)inventory.controls++;if(surfaces)inventory.surfaces++;if(/\bh[1-6]\b|\bfont|title|label/.test(rule.selector))inventory.text++;if(process.argv.includes('--consolidate')&&(controls||surfaces))rule.walkDecls(d=>{if(own.test(d.prop)){d.remove();inventory.removed++;}});});return tree.toString();}
for(const file of files){if(!fs.existsSync(file))continue;const old=fs.readFileSync(file,'utf8');const transform=css=>process.argv.includes('--tokenize')?tokenize(processCSS(css,file)):processCSS(css,file);const updated=file.endsWith('.html')?old.replace(/(<style\b[^>]*>)([\s\S]*?)(<\/style>)/gi,(_,a,css,b)=>a+transform(css)+b):transform(old);if(process.argv.includes('--consolidate')||process.argv.includes('--tokenize'))fs.writeFileSync(file,updated);}
console.log(JSON.stringify(counters,null,2));
