// Reuse the exact football board math; no separate model or retrospectively rebuilt picks.
const fs=require('fs'),path=require('path'),vm=require('vm'),{JSDOM}=require('jsdom');
(async()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');const dom=new JSDOM(html,{url:'https://going-long.vercel.app/long/',runScripts:'outside-only',pretendToBeVisual:true});
try{const w=dom.window;w.localStorage.setItem('goinglong.gateway.mode','fantasy');w.requestAnimationFrame=cb=>w.setTimeout(cb,0);w.HTMLElement.prototype.scrollIntoView=function(){};
const ctx=dom.getInternalVMContext();for(const s of w.document.querySelectorAll('script:not([src])'))vm.runInContext(s.textContent.replace(/\nboot\(\);/,'\n'),ctx);
const data=name=>{const live=path.join(process.env.TOPDOWN_DATA_ROOT||root,'data',name);return JSON.parse(fs.readFileSync(fs.existsSync(live)?live:path.join(root,'data',name),'utf8'));};ctx.inputs={history:data('history.json'),config:data('data.json'),context:data('football_context.json')};
const feeds=await Promise.all(['nfl','ncaa'].map(async sport=>{const r=await fetch('https://going-long.vercel.app/api/odds?sport='+sport,{signal:AbortSignal.timeout(50000)});if(!r.ok)throw Error(sport+' odds unavailable');return r.json();}));ctx.feeds=feeds;
const rows=await vm.runInContext(`(async()=>{BET.history=inputs.history.betting;BET.config=inputs.config.betting||{};BET.context=inputs.context;BET.nflData=feeds[0];BET.ncaaData=feeds[1];BET.liveLoaded={nfl:true,ncaa:true};BET.props=await propsFromRealData();BET.games=gamesFromRealData();const rows=await signalCandidates(),prices=bestPriceCandidates(),out=[];const now=Date.now();for(const c of rows){if(Date.parse(c.kickoff)>now&&footballDate(c.kickoff)===footballDate(now)&&Number.isFinite(c.prob))out.push({...c,tracking_group:'all_projection'});}for(const sport of ['nfl','ncaa']){const ranked=rankBestPlays([...rows,...prices],[...(SIGNAL.allQuotes||[]),...prices],sport,'all',now);for(const c of ranked.chance)out.push({...c,tracking_group:'best_model'});for(const c of ranked.value)out.push({...c,tracking_group:'best_value'});}return out;})()`,ctx);process.stdout.write(JSON.stringify(rows));
}finally{dom.window.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
