// Reuse the exact football board math; no separate model or retrospectively rebuilt picks.
const fs=require('fs'),path=require('path'),vm=require('vm'),{createHash}=require('node:crypto'),{JSDOM}=require('jsdom');
const {captureReadiness}=require('../shared/football-readiness-snapshot.cjs');
const {fingerprint}=require('../shared/football-picks-snapshot.cjs');
const sha256=value=>createHash('sha256').update(value).digest('hex');
(async()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');const dom=new JSDOM(html,{url:'https://going-long.vercel.app/long/',runScripts:'outside-only',pretendToBeVisual:true});
try{const w=dom.window;w.GoingFootballOpportunity=require('../shared/football-opportunity.js');w.GoingFootballInjuries=require('../shared/football-injuries.js');w.GoingScoreTracker=require('../shared/score-tracker.js');w.localStorage.setItem('goinglong.gateway.mode','fantasy');w.requestAnimationFrame=cb=>w.setTimeout(cb,0);w.HTMLElement.prototype.scrollIntoView=function(){};
const ctx=dom.getInternalVMContext();for(const asset of ['going-eligibility','going-intel','football-confidence','football-picks'])vm.runInContext(fs.readFileSync(path.join(root,'shared',asset+'.js'),'utf8'),ctx);for(const s of w.document.querySelectorAll('script:not([src])'))vm.runInContext(s.textContent.replace(/\nboot\(\);/,'\n'),ctx);
const provenance={schema_version:1,model_source_sha256:sha256(html),inputs:{}};
ctx.captureQuotes=process.env.GOING_CAPTURE_QUOTES==='1';
const data=name=>{const live=path.join(process.env.TOPDOWN_DATA_ROOT||root,'data',name),body=fs.readFileSync(fs.existsSync(live)?live:path.join(root,'data',name),'utf8'),parsed=JSON.parse(body);provenance.inputs[name]={sha256:sha256(body),generated_at:parsed.betting?.generated_at||parsed.generated_at||null};return parsed;};ctx.inputs={history:data('history.json'),config:data('data.json'),context:data('football_context.json'),injuryLearning:data('injury_context.json'),roster:data('players.json')};
const feeds=process.env.GOING_TRACKER_LOCAL_DATA==='1'
 ? [data('nfl_betting.json'),data('ncaa_lines.json')]
 : await Promise.all(['nfl','ncaa'].map(async sport=>{const r=await fetch('https://going-long.vercel.app/api/odds?sport='+sport,{signal:AbortSignal.timeout(50000)});if(!r.ok)throw Error(sport+' odds unavailable');const body=await r.text(),parsed=JSON.parse(body),name=sport==='nfl'?'nfl_betting.json':'ncaa_lines.json';provenance.inputs[name]={sha256:sha256(body),generated_at:parsed.generated_at||null};return parsed;}));ctx.feeds=feeds;
let learning=null,results=null;try{learning=data('season_learning.json');}catch{}try{results=data('results.json');}catch{}
ctx.pickLearning=learning;ctx.pickResults=results;
// Capture after every evidence source has been read; this timestamp does not feed ranking.
const capturedAt=new Date().toISOString();
const assessorSha=sha256(fs.readFileSync(path.join(root,'shared/football-confidence.js'))),inputRef=name=>provenance.inputs[name]?{sha256:provenance.inputs[name].sha256,generated_at:provenance.inputs[name].generated_at}:{unavailable:true};
const rows=await vm.runInContext(`(async()=>{BET.history=inputs.history.betting;BET.config=inputs.config.betting||{};BET.context=inputs.context;BET.roster=inputs.roster;BET.injuryLearning=inputs.injuryLearning;BET.injuryContext=GoingFootballInjuries.createContext(BET.roster,BET.history?.profiles,Date.now(),BET.injuryLearning);BET.nflData=feeds[0];BET.ncaaData=feeds[1];BET.liveLoaded={nfl:true,ncaa:true};BET.props=markUnavailableProps(await propsFromRealData());BET.games=gamesFromRealData();const rows=await signalCandidates(),prices=bestPriceCandidates(),out=[];const now=Date.now();for(const c of rows){if(Date.parse(c.kickoff)>now&&footballDate(c.kickoff)===footballDate(now)&&Number.isFinite(c.prob))out.push({...c,tracking_group:'all_projection'});}for(const sport of ['nfl','ncaa']){const ranked=rankBestPlays([...rows,...prices],[...(SIGNAL.allQuotes||[]),...prices],sport,'all',now);for(const c of ranked.chance)out.push({...c,tracking_group:'best_model'});for(const c of ranked.value)out.push({...c,tracking_group:'best_value'});}if(globalThis.captureQuotes)out.push(...(SIGNAL.allQuotes||[]).map(q=>({sport:q.sport,home:q.home,away:q.away,kickoff:q.kickoff,profileId:q.profileId,market:q.market,line:q.line,side:q.side,book:q.book,dec:q.dec,updatedAt:q.updatedAt,reference:q.reference,tracking_group:'quote_only'})));return out;})()`,ctx);
const season=ctx.inputs.history.betting?.season_review?.season;
// A separate versioned research board; never relabel old model records.
ctx.pickCapturedAt=capturedAt;ctx.pickProvenance=provenance;
const pickRows=vm.runInContext(`(()=>{BET.learning=pickLearning;CONFIDENCE_RESULTS=pickResults;const now=Date.parse(pickCapturedAt),board=GoingFootballPicks.board(goingPicksCandidates(now),c=>({...confidenceEvidenceOptions(c),now,context:BET.context,injuryLearning:BET.injuryLearning}));return board.picks.filter(x=>x.evidence.interesting&&!x.evidence.tdResearch).map((x,i)=>({...x.candidate,tracking_group:'going_picks_v3',model_cohort:'going-picks-v3',picks_snapshot:{version:GoingFootballPicks.VERSION,captured_at:pickCapturedAt,rank:i+1,rating:x.evidence.rating,evidenceTier:x.evidence.evidenceTier,ratingDetail:x.evidence.ratingDetail,points:x.evidence.points,badges:x.evidence.badges,components:x.evidence.components,facts:x.evidence.facts,unknown:x.evidence.unknown,why:x.evidence.why,concern:x.evidence.concern,price:x.evidence.price,injury:x.candidate.injury||null,offers:x.offers,source_inputs:pickProvenance.inputs}}));})()`,ctx);
provenance.picks_assessor_sha256=sha256(fs.readFileSync(path.join(root,'shared/football-picks.js')));for(const row of pickRows)row.picks_snapshot.candidate_sha256=fingerprint(row);rows.push(...pickRows);
const readiness=row=>captureReadiness({...row,readiness_inputs:{history:inputRef('history.json'),context:inputRef('football_context.json'),learning:inputRef('season_learning.json'),results:inputRef('results.json'),config:inputRef('data.json'),injury:inputRef('injury_context.json'),roster:inputRef('players.json'),nfl_feed:inputRef('nfl_betting.json'),ncaa_feed:inputRef('ncaa_lines.json')}},{capturedAt,season,historyAt:ctx.inputs.history.betting?.generated_at,contextAt:ctx.inputs.context.generated_at,learningAt:learning?.generated_at,resultsAt:results?.generated_at,history:ctx.inputs.history.betting,results,learning,historyHash:provenance.inputs['history.json']?.sha256,contextHash:provenance.inputs['football_context.json']?.sha256,learningHash:provenance.inputs['season_learning.json']?.sha256,resultsHash:provenance.inputs['results.json']?.sha256,assessorHash:assessorSha,historyInputAt:provenance.inputs['history.json']?.generated_at,contextInputAt:provenance.inputs['football_context.json']?.generated_at,learningInputAt:provenance.inputs['season_learning.json']?.generated_at,resultsInputAt:provenance.inputs['results.json']?.generated_at});
provenance.readiness_assessor_sha256=assessorSha;process.stdout.write(JSON.stringify(rows.map(row=>row.tracking_group==='quote_only'?row:({...row,provenance,readiness_snapshot:readiness(row)}))));
}finally{dom.window.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
