#!/usr/bin/env python
"""Trend Intelligence research runner (research only).

    python scripts/trend_research.py register            pre-register every spec in the ledger (hash stored before any run)
    python scripts/trend_research.py run E1 [E2 ...]      run pre-registered experiments and record aggregate results
    python scripts/trend_research.py show                 print the ledger

Reads the local, licensed Fantasy Points archive (never committed) and public nflverse weekly stats. Only aggregate metrics are written to
research/trend-intelligence/ledger.json.
"""
import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fp_ingest.store import Manifest, find_root  # noqa: E402
from trend_research import experiments, experiments2, experiments3, experiments4, experiments5, ledger  # noqa: E402

SPECS = {**experiments.SPECS, **experiments2.SPECS, **experiments3.SPECS, **experiments4.SPECS, **experiments5.SPECS}
RUNNERS = {**experiments.RUNNERS, **experiments2.RUNNERS, **experiments3.RUNNERS, **experiments4.RUNNERS, **experiments5.RUNNERS}

REPO = Path(__file__).resolve().parents[1]


def cmd_register(args):
    book = ledger.load()
    for spec in SPECS.values():
        entry = ledger.register(book, spec)
        print(f"{spec['id']}: {entry['status']} spec {entry['spec_sha256'][:12]} registered {entry['registered_at']}")
    ledger.save(book)
    return 0


def cmd_run(args):
    root = find_root(args.root, REPO)
    manifest = Manifest(root)
    book = ledger.load()
    for exp_id in args.ids:
        spec = SPECS[exp_id]
        if exp_id not in book['experiments']:
            raise SystemExit(f'{exp_id} is not pre-registered; run `register` first')
        started = time.time()
        result, status = RUNNERS[exp_id](root, manifest)
        result['seconds'] = round(time.time() - started, 1)
        ledger.record(book, exp_id, spec, result, status)
        ledger.save(book)
        print(f'{exp_id}: {status} ({result["seconds"]}s)')
    return 0


def cmd_sensitivity(args):
    root = find_root(args.root, REPO)
    book = ledger.load()
    book['sensitivity'] = experiments.sensitivity(root, Manifest(root))
    ledger.save(book)
    print('sensitivity recorded')
    return 0


def cmd_benchmark(args):
    root = find_root(args.root, REPO)
    from tracker_store import load_tracker
    from trend_research import benchmarks_run
    records = load_tracker(str(REPO / 'data'))['records']
    result = benchmarks_run.run(root, records, REPO / 'research' / 'trend-intelligence' / 'champion_benchmark.json')
    print('player markets:', {m: round(sum(v['mae'] * v['n'] for v in b.values()) / sum(v['n'] for v in b.values()), 3) for m, b in result['player_mean_accuracy_reconstructed_champion'].items()})
    print('game model vs market (pooled):', {k: round(v, 2) for k, v in result['game_model_vs_closing_market']['pooled'].items()})
    return 0


def cmd_outcomes(args):
    root = find_root(args.root, REPO)
    from trend_research import prospective
    written = prospective.write_outcomes(root, args.season, refresh=True)
    print('wrote', written or 'nothing new (an outcome file needs a completed NFL week)')
    return 0


def cmd_show(args):
    book = ledger.load()
    for exp_id, entry in book['experiments'].items():
        print(f"{exp_id} [{entry['status']}] {entry['spec']['title']}")
    return 0


def cmd_report(args):
    """Write research/trend-intelligence/LEDGER.md from the ledger and interpretations (aggregate numbers only)."""
    book = ledger.load()
    notes = json.loads((REPO / 'research' / 'trend-intelligence' / 'interpretations.json').read_text(encoding='utf-8'))
    signals = json.loads((REPO / 'research' / 'trend-intelligence' / 'candidate_signals.json').read_text(encoding='utf-8'))['signals']
    lines = ['# Research ledger', '', 'Generated by `python scripts/trend_research.py report`. Aggregate results only; negative findings are kept on purpose.', '',
             '| Experiment | Status | Question |', '| --- | --- | --- |']
    for exp_id, entry in book['experiments'].items():
        lines.append(f"| {exp_id} | **{entry['status']}** | {entry['spec']['title']} |")
    for exp_id, entry in book['experiments'].items():
        spec, result, note = entry['spec'], entry['result'], notes.get(exp_id, {})
        lines += ['', f"## {exp_id}: {spec['title']} - {entry['status']}", '', f"*Pre-registered {entry['registered_at']} (spec `{entry['spec_sha256'][:12]}`).*"]
        if spec.get('exploratory'):
            lines.append('*Exploratory, post-hoc: cannot support promotion.*')
        lines += ['', f"- **What we thought:** {note.get('thought', spec['hypothesis'])}", f"- **Why football supports it:** {spec.get('football_rationale', '')}",
                  f"- **How tested without leakage:** {spec['leakage']}; chronological rolling origin; comparators {json.dumps(spec.get('baselines') or spec.get('models') or spec.get('comparators') or spec.get('primary_comparison'))}",
                  f"- **Result:** {note.get('result', '')}", f"- **What GOING should do:** {note.get('action', '')}"]
        if result:
            lines += ['', '| Outcome / bucket | Verdict | Baseline MAE | Challenger MAE | Rel. improvement | 95%-adj CI of delta | Seasons better | n |', '| --- | --- | --- | --- | --- | --- | --- | --- |']
            groups = result.get('outcomes') or {}
            if 'buckets' in result:
                groups = {f'{b} / {o}': r for b, outs in result['buckets'].items() for o, r in outs.items()}
            elif exp_id == 'E7':
                groups = {f'{m} (weeks 1-6, blend vs Champion)': r['primary_weeks1_6_W3_vs_W0'] for m, r in result['markets'].items()}
                groups.update({f'{m} (all weeks)': r['all_weeks_W3_vs_W0'] for m, r in result['markets'].items()})
            elif exp_id == 'E8':
                groups = {f'{m}: {name}': c for m, r in result['markets'].items() for name, c in r['comparisons'].items()}
            elif exp_id == 'E9':
                groups = {f'{m}: {name}': c for m, r in result['outcomes'].items() for name, c in r['comparisons'].items()}
            elif exp_id == 'E10':
                groups = {}
                for m, r in result['markets'].items():
                    if 'brier_w3' in r:
                        lines.append(f"| {m} (Brier, 2026 frozen) | {r['verdict']} | {r['brier_champion']:.4f} | {r['brier_w3']:.4f} | {r['relative_improvement'] * 100:+.2f}% | [{r['delta_brier_ci95'][0]:+.4f}, {r['delta_brier_ci95'][1]:+.4f}] | n/a | {r['n']} |")
            for name, res in groups.items():
                p = res['pooled']
                lines.append(f"| {name} | {res['verdict']} | {p['base_mae']:.4g} | {p['new_mae']:.4g} | {p['relative_improvement'] * 100:+.2f}% | [{p['ci_low']:+.3g}, {p['ci_high']:+.3g}] | {p['years_better']}/{p['years_total']} | {p['n']} |")
    sens = book.get('sensitivity')
    if sens:
        lines += ['', '## Robustness checks (added after independent QA; the registered verdicts stand)', '',
                  'Relative MAE gain of the challenger over its baseline when the ridge penalty or sample filter changes (positive = challenger better).', '',
                  '| Check | ' + ' | '.join(f'alpha {a:g}' for a in sens['alphas']) + ' |', '| --- | ' + ' | '.join('---' for _ in sens['alphas']) + ' |']
        for label in ('E1', 'E6'):
            for outcome, rows in sens[label].items():
                lines.append(f'| {label} {outcome} | ' + ' | '.join(f"{rows[str(a)]['relative_gain'] * 100:+.2f}%" for a in sens['alphas']) + ' |')
        for name, rows in sens['E2_fp_per_game'].items():
            if 'baseline_mae' in rows:
                lines.append(f"| E2 FP/G {name} | XFP gain over a baseline that already has raw targets and carries per game: {rows['xfp_gain_over_volume_baseline'] * 100:+.2f}% | | | |")
            else:
                lines.append(f'| E2 FP/G {name} | ' + ' | '.join(f"{rows[str(a)]['relative_gain'] * 100:+.2f}%" for a in sens['alphas']) + ' |')
    lines += ['', '## Candidate signal map (ranked)', '', '| Priority | Signal | Class | Markets | Seasons | Experiments |', '| --- | --- | --- | --- | --- | --- |']
    for signal in sorted(signals, key=lambda x: -(x['betting_value'] * x['data_quality'] * x['testability'])):
        score = signal['betting_value'] * signal['data_quality'] * signal['testability']
        lines.append(f"| {score} | {signal['family']}: {signal['signal']} | {signal['evidence_class']} | {', '.join(signal['markets'])} | {signal['seasons']} | {', '.join(signal['experiments']) or '-'} |")
    out = REPO / 'research' / 'trend-intelligence' / 'LEDGER.md'
    out.write_text(chr(10).join(lines) + chr(10), encoding='utf-8')
    print('wrote', out)
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--root')
    sub = parser.add_subparsers(dest='command', required=True)
    sub.add_parser('register').set_defaults(func=cmd_register)
    p = sub.add_parser('run')
    p.add_argument('ids', nargs='+')
    p.set_defaults(func=cmd_run)
    sub.add_parser('show').set_defaults(func=cmd_show)
    sub.add_parser('benchmark').set_defaults(func=cmd_benchmark)
    p = sub.add_parser('outcomes')
    p.add_argument('--season', type=int, default=2026)
    p.set_defaults(func=cmd_outcomes)
    sub.add_parser('sensitivity').set_defaults(func=cmd_sensitivity)
    sub.add_parser('report').set_defaults(func=cmd_report)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
