/* Builds the derived Validation light ledger from the canonical segmented tracker store.
 *
 * Output: data/derived/validation_ledger/ledger-<seg>-<src12>-<own12>.json (one per store segment) and
 * index.json (written LAST). Everything is a pure, deterministic function of the store (no clocks, no
 * randomness), so it can be deleted and regenerated byte-for-byte. This module is never imported by the tracker
 * writer, calibration, settlement or audits; the ledger is a UI projection only (shared/validation-ledger.mjs).
 */
import {writeFile,rename,mkdir,readdir,unlink,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readTrackerStore} from './tracker_store.mjs';
import {LEDGER_LAYOUT,PROJECTION_VERSION,projectRecord,seasonOf,STORE_LAYOUT} from '../shared/validation-ledger.mjs';

export const LEDGER_DIR=path.join('derived','validation_ledger');
export const MAX_FILE_BYTES=30e6,WARN_FILE_BYTES=8e6;
const FILE=/^(index|ledger-\d{6}-[0-9a-f]{12}-[0-9a-f]{12})\.json(\.tmp)?$/;
const sha=text=>createHash('sha256').update(text).digest('hex');
const shardName=(i,src,own)=>`ledger-${String(i+1).padStart(6,'0')}-${src.slice(0,12)}-${own.slice(0,12)}.json`;

async function saveIfChanged(file,text){
 let existing=null;try{existing=await readFile(file,'utf8');}catch{}
 if(existing===text)return false;
 await writeFile(file+'.tmp',text);await rename(file+'.tmp',file);return true;
}

export async function buildValidationLedger({dataDir}){
 const store=await readTrackerStore(dataDir);
 if(!store)throw new Error('No tracker store to project');
 const {manifest,snapshot}=store,records=snapshot.records;
 // Season of every prediction, so a settlement/closing shard also names the seasons of the predictions it concerns.
 const predSeason=new Map();
 for(const r of records)if(r.kind==='prediction')predSeason.set(r.payload.id||r.id,seasonOf(r.payload.kickoff));
 const dir=path.join(dataDir,LEDGER_DIR);await mkdir(dir,{recursive:true});
 const shards=[],texts=[];let totalRows=0,totalBytes=0;
 manifest.segments.forEach((seg,i)=>{
  const slice=records.slice(seg.first_record,seg.first_record+seg.records),rows=slice.map(projectRecord).filter(Boolean);
  const seasons=new Set();
  for(const r of rows){
   const s=r.kind==='prediction'?seasonOf(r.payload.kickoff):predSeason.get(r.payload.prediction_id);
   if(s!==null&&s!==undefined)seasons.add(s);
  }
  const body=JSON.stringify({schema_version:1,layout:LEDGER_LAYOUT,projection_version:PROJECTION_VERSION,derived:true,not_for_evaluation:true,
   source:{segment_file:seg.file,segment_sha256:seg.sha256,first_record:seg.first_record,records:seg.records},rows});
  const bytes=Buffer.byteLength(body);
  if(bytes>MAX_FILE_BYTES)throw new Error(`Validation ledger shard ${i+1} is ${bytes} bytes, over the limit; refusing to write`);
  if(bytes>WARN_FILE_BYTES)console.warn(`Validation ledger shard ${i+1} is ${bytes} bytes`);
  const own=sha(body),file=shardName(i,seg.sha256,own);
  const kicks=rows.filter(r=>r.kind==='prediction').map(r=>Date.parse(r.payload.kickoff)).filter(Number.isFinite);
  texts.push([file,body]);
  shards.push({file,sha256:own,bytes,rows:rows.length,source_index:i,source_segment_sha256:seg.sha256,source_records:seg.records,
   seasons:[...seasons].sort((a,b)=>a-b),kickoff_min:kicks.length?new Date(Math.min(...kicks)).toISOString():null,kickoff_max:kicks.length?new Date(Math.max(...kicks)).toISOString():null,
   first_observed_at:rows[0]?.observed_at??null,last_observed_at:rows.at(-1)?.observed_at??null});
  totalRows+=rows.length;totalBytes+=bytes;
 });
 const index={schema_version:1,layout:LEDGER_LAYOUT,projection_version:PROJECTION_VERSION,derived:true,not_for_evaluation:true,
  note:'Derived projection of the canonical tracker store for the Validation dashboard. Never an input to the writer, calibration, settlement or audits; delete and regenerate freely.',
  source:{store_layout:STORE_LAYOUT,manifest_generated_at:manifest.generated_at??null,total_records:manifest.total_records,
   segments:manifest.segments.map(s=>({file:s.file,sha256:s.sha256,first_record:s.first_record,records:s.records}))},
  shards,totals:{rows:totalRows,bytes:totalBytes,shards:shards.length}};
 const indexText=JSON.stringify(index);
 let rewritten=0;
 for(const [file,text] of texts)if(await saveIfChanged(path.join(dir,file),text))rewritten++;
 await saveIfChanged(path.join(dir,'index.json'),indexText); // last: every shard it names already exists
 const keep=new Set(['index.json',...shards.map(s=>s.file)]);let removed=0;
 for(const name of await readdir(dir))if(FILE.test(name)&&!keep.has(name)){await unlink(path.join(dir,name));removed++;}
 return {shards:shards.length,rows:totalRows,bytes:totalBytes,largest:Math.max(...shards.map(s=>s.bytes)),index_bytes:Buffer.byteLength(indexText),rewritten,removed};
}

if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)&&process.argv[2]==='build'){
 const dataDir=path.resolve(process.argv[3]||path.join(path.dirname(fileURLToPath(import.meta.url)),'..','data'));
 console.log(JSON.stringify(await buildValidationLedger({dataDir})));
}
